### load in the csv data as df first

In [7]:
import pandas as pd

df_2024_2025 = pd.read_csv("nba_2024_to_2025_season_per_player_data.csv")
df_2023_2024 = pd.read_csv("nba_2023_to_2024_season_per_player_data.csv")
full_data = pd.concat([df_2023_2024, df_2024_2025], ignore_index = True)
full_data

# citation for data:
# https://www.basketball-reference.com/leagues/NBA_2024_totals.html

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,Awards,Player-additional
0,1,Luka Dončić,24,DAL,PG,70,70,2624,804,1652,...,647,686,99,38,282,149,2370,21,MVP-3CPOY-6ASNBA1,doncilu01
1,2,Shai Gilgeous-Alexander,25,OKC,PG,75,75,2553,796,1487,...,415,465,150,67,162,184,2254,0,MVP-2DPOY-7CPOY-3ASNBA1,gilgesh01
2,3,Giannis Antetokounmpo,29,MIL,PF,73,73,2567,837,1369,...,841,476,87,79,250,210,2222,10,MVP-4DPOY-9CPOY-12ASNBA1,antetgi01
3,4,Jalen Brunson,27,NYK,PG,77,77,2726,790,1648,...,278,519,70,13,186,144,2212,0,MVP-5CPOY-5ASNBA2,brunsja01
4,5,Nikola Jokić,28,DEN,C,79,79,2737,822,1411,...,976,708,108,68,237,194,2085,25,MVP-1CPOY-4ASNBA1,jokicni01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,565,Riley Minix,24,SAS,SF,1,0,7,0,1,...,2,0,0,0,0,0,0,0,NaN,minixri01
1466,566,Jahlil Okafor,29,IND,C,1,0,3,0,0,...,1,1,0,0,0,0,0,0,NaN,okafoja01
1467,567,Zyon Pullin,23,MEM,SG,3,0,3,0,1,...,0,0,0,0,0,0,0,0,NaN,pullizy01
1468,568,Isaiah Stevens,24,MIA,PG,3,0,6,0,2,...,2,0,1,0,0,0,0,0,NaN,steveis01
1469,569,Terry Taylor,25,SAC,PF,3,0,6,0,1,...,1,2,0,0,0,0,0,0,NaN,taylote01

### Connect to sql, create table, load the dataframe in the created table with StringIO.

In [2]:
import psycopg
import pandas as pd

In [3]:
conninfo = "host=localhost port=5433 dbname=final_project user=postgres password=Samantha910918*"
conn = psycopg.connect(conninfo)
cur = conn.cursor()

In [4]:
def execute_sql(sql, params=None):
    """
    For creating tables, inserting into tables.
    """
    with psycopg.connect(conninfo) as conn:
        with conn.cursor() as cur:
            cur.execute(sql, params)
        conn.commit()

In [5]:
def query_df(sql, params=None):
    """
    For running queries. Returns pandas dataframe of query ouput.
    """
    with psycopg.connect(conninfo) as conn:
        with conn.cursor() as cur:
            cur.execute(sql, params)
            cols = [d.name for d in cur.description]
            return pd.DataFrame(cur.fetchall(), columns=cols)

In [137]:
full_data.columns

Index(['player_rank_per_season', 'player_name', 'age', 'team', 'pos', 'games',
       'games_started', 'mins_played', 'field_goals', 'field_goals_attempts',
       'field_goals_percentage', 'three_pointer', 'three_pointer_attempts',
       'three_pointer_percentage', 'two_pointer', 'two_pointer_attempts',
       'two_pointer_percentage', 'effective_field_goal_percentagefree_throw',
       'free_throw_attempts', 'free_throw_percentage', 'offensive_rebound',
       'defensive_rebound', 'total_rebound', 'assist', 'steal', 'block',
       'turnover', 'personal_foul', 'points', 'triple_double', 'awards',
       'player_additional', 'Player-additional'],
      dtype='object')

In [145]:
sql = """
CREATE TABLE nba_data (
player_rank_per_season INT,
player_name TEXT,
age INT,
team TEXT,
pos TEXT,
games INT,
games_started INT,
mins_played NUMERIC(6,2),
field_goals INT,
field_goals_attempts INT,
field_goals_percentage DECIMAL(5,3),
three_pointer INT,
three_pointer_attempts INT,
three_pointer_percentage DECIMAL(5,3),
two_pointer INT,
two_pointer_attempts INT,
two_pointer_percentage DECIMAL(5,3),
effective_field_goal_percentage DECIMAL(5,3),
free_throw INT,
free_throw_attempts INT,
free_throw_percentage DECIMAL(5,3),
offensive_rebound INT,
defensive_rebound INT,
total_rebound INT,
assist INT,
steal INT,
block INT,
turnover INT,
personal_foul INT,
points INT,
triple_double INT,
awards TEXT,
player_additional TEXT
);

CREATE TABLE nba_data_2023_2024 (
player_rank_per_season INT,
player_name TEXT,
age INT,
team TEXT,
pos TEXT,
games INT,
games_started INT,
mins_played NUMERIC(6,2),
field_goals INT,
field_goals_attempts INT,
field_goals_percentage DECIMAL(5,3),
three_pointer INT,
three_pointer_attempts INT,
three_pointer_percentage DECIMAL(5,3),
two_pointer INT,
two_pointer_attempts INT,
two_pointer_percentage DECIMAL(5,3),
effective_field_goal_percentage DECIMAL(5,3),
free_throw INT,
free_throw_attempts INT,
free_throw_percentage DECIMAL(5,3),
offensive_rebound INT,
defensive_rebound INT,
total_rebound INT,
assist INT,
steal INT,
block INT,
turnover INT,
personal_foul INT,
points INT,
triple_double INT,
awards TEXT,
player_additional TEXT
);

CREATE TABLE nba_data_2024_2025 (
player_rank_per_season INT,
player_name TEXT,
age INT,
team TEXT,
pos TEXT,
games INT,
games_started INT,
mins_played NUMERIC(6,2),
field_goals INT,
field_goals_attempts INT,
field_goals_percentage DECIMAL(5,3),
three_pointer INT,
three_pointer_attempts INT,
three_pointer_percentage DECIMAL(5,3),
two_pointer INT,
two_pointer_attempts INT,
two_pointer_percentage DECIMAL(5,3),
effective_field_goal_percentage DECIMAL(5,3),
free_throw INT,
free_throw_attempts INT,
free_throw_percentage DECIMAL(5,3),
offensive_rebound INT,
defensive_rebound INT,
total_rebound INT,
assist INT,
steal INT,
block INT,
turnover INT,
personal_foul INT,
points INT,
triple_double INT,
awards TEXT,
player_additional TEXT
);
"""

In [146]:
# sql = """
# DROP TABLE IF EXISTS nba_data;
# DROP TABLE IF EXISTS nba_data_2023_2024;
# DROP TABLE IF EXISTS nba_data_2024_2025;
# """

In [147]:
execute_sql(sql)

In [148]:
# rename full_data col so it matches with the sql query create table.
sql_table_col_names = ["player_rank_per_season", "player_name", "age", "team", "pos", "games", 
                       "games_started", "mins_played", "field_goals", "field_goals_attempts", "field_goals_percentage",
                       "three_pointer", "three_pointer_attempts", "three_pointer_percentage",
                       "two_pointer", "two_pointer_attempts", "two_pointer_percentage", "effective_field_goal_percentage"
                       "free_throw", "free_throw_attempts", "free_throw_percentage",
                       "offensive_rebound", "defensive_rebound", "total_rebound", 
                       "assist", "steal", "block", "turnover", "personal_foul",
                       "points", "triple_double", "awards", "player_additional"]
full_data = full_data.rename(columns = dict(zip(full_data.columns, sql_table_col_names)))
df_2024_2025 = df_2024_2025.rename(columns = dict(zip(df_2024_2025.columns, sql_table_col_names)))
df_2023_2024 = df_2023_2024.rename(columns = dict(zip(df_2023_2024.columns, sql_table_col_names)))
full_data.head(1)

,player_rank_per_season,player_name,age,team,pos,games,games_started,mins_played,field_goals,field_goals_attempts,...,assist,steal,block,turnover,personal_foul,points,triple_double,awards,player_additional,Player-additional
0,1,Luka Dončić,24,DAL,PG,70,70,2624,804,1652,...,647,686,99,38,282,149,2370,21,MVP-3CPOY-6ASNBA1,doncilu01

In [ ]:
# conn.rollback()

In [151]:
from io import StringIO

full_data = full_data.rename(columns = dict(zip(full_data.columns, sql_table_col_names)))
df_names = [full_data, df_2024_2025, df_2023_2024]
sql_table_names = ["nba_data", "nba_data_2024_2025", "nba_data_2023_2024"]
for i in range(len(df_names)):
    buffer = StringIO()
    df_names[i].to_csv(buffer, index=False, header=True)
    buffer.seek(0)

    with conn.cursor() as cur:
        with cur.copy("COPY " + sql_table_names[i] + "(player_rank_per_season, player_name, age, team, pos, "
                    "games, games_started, mins_played, "
                    "field_goals, field_goals_attempts, field_goals_percentage, "
                    "three_pointer, three_pointer_attempts, three_pointer_percentage, "
                    "two_pointer, two_pointer_attempts, two_pointer_percentage, effective_field_goal_percentage,"
                    "free_throw, free_throw_attempts, free_throw_percentage, "
                    "offensive_rebound, defensive_rebound, total_rebound, "
                    "assist, steal, block, turnover, personal_foul, "
                    "points, triple_double, awards, player_additional) "
                    "FROM STDIN WITH CSV HEADER") as copy:
            copy.write(buffer.getvalue())

    conn.commit()
    print("Data loaded successfully")
    
conn.close()
# citation
# got help from llm to convert dataframe to sql query without having to manually write out the whole data by hand

Data loaded successfully
Data loaded successfully
Data loaded successfully

### Begin Analysis

##### Look for top 5 players that played in both 2023-2024 and 2024-2025 season by different stats

1. top 5 players by overall player rank that played in both seasons

In [ ]:
query = """
WITH calc_overall_avg_rank AS(
SELECT nd2324.player_name, 
    (nd2324.player_rank_per_season + nd2425.player_rank_per_season) / 2 AS avg_player_rank_over_two_seasons
FROM nba_data_2023_2024 nd2324
LEFT JOIN nba_data_2024_2025 nd2425
ON nd2324.player_name = nd2425.player_name
WHERE nd2324.player_rank_per_season IS NOT NULL and nd2425.player_rank_per_season IS NOT NULL
GROUP BY nd2324.player_name, nd2324.player_rank_per_season, nd2425.player_rank_per_season
)
SELECT coar.player_name, coar.avg_player_rank_over_two_seasons
FROM calc_overall_avg_rank coar
ORDER BY coar.avg_player_rank_over_two_seasons ASC
LIMIT 5;
"""

In [200]:
df = query_df(query)

In [201]:
df

               player_name  avg_player_rank_over_two_seasons
0  Shai Gilgeous-Alexander                                 1
1    Giannis Antetokounmpo                                 3
2             Nikola Jokić                                 4
3          Anthony Edwards                                 4
4             Jayson Tatum                                 6

2. top 5 players by field_goals_percentage that has a field goal attempt greater than the mean field goal attempt

In [359]:
query = """
WITH calc_avg_fga AS (
SELECT AVG(field_goals_attempts) AS average_fga
FROM nba_data
WHERE field_goals_attempts IS NOT NULL AND field_goals_attempts > 0
),
calc_overall_field_goals_attempts AS(
SELECT nd2324.player_name, nd2324.team,
(nd2324.field_goals_attempts + nd2425.field_goals_attempts) / 2 AS avg_fga_over_two_seasons,
(nd2324.field_goals_percentage + nd2425.field_goals_percentage) / 2 AS avg_fgp_over_two_seasons
FROM nba_data_2023_2024 nd2324
LEFT JOIN nba_data_2024_2025 nd2425
ON nd2324.player_name = nd2425.player_name
WHERE nd2324.player_rank_per_season IS NOT NULL and nd2425.player_rank_per_season IS NOT NULL
GROUP BY nd2324.player_name, nd2324.team, nd2324.field_goals_attempts, nd2425.field_goals_attempts, nd2324.field_goals_percentage, nd2425.field_goals_percentage
)
SELECT cofga.player_name, cofga.team,
ROUND(cofga.avg_fgp_over_two_seasons * 100, 2) AS avg_fgp_over_two_seasons
FROM calc_overall_field_goals_attempts cofga
CROSS JOIN calc_avg_fga caf
WHERE cofga.avg_fga_over_two_seasons > caf.average_fga
ORDER BY cofga.avg_fgp_over_two_seasons DESC
LIMIT 5;
"""

In [360]:
df = query_df(query)

In [361]:
df

      player_name team avg_fgp_over_two_seasons
0  Daniel Gafford  2TM                    71.35
1  Daniel Gafford  WAS                    69.60
2   Jarrett Allen  CLE                    67.00
3     Rudy Gobert  MIN                    66.50
4  Walker Kessler  UTA                    65.85

3. top 5 players by two_pointer_percentage that has a two_pointer_attempt greater than the mean two_pointer_attempt

In [254]:
query = """
WITH calc_avg_tpa AS (
SELECT AVG(two_pointer_attempts) AS average_tpa
FROM nba_data
WHERE two_pointer_attempts IS NOT NULL AND two_pointer_attempts > 0
),
calc_overall_two_pointer_attempts AS(
SELECT nd2324.player_name, nd2324.team,
(nd2324.two_pointer_attempts + nd2425.two_pointer_attempts) / 2 AS avg_tpa_over_two_seasons,
(nd2324.two_pointer_percentage + nd2425.two_pointer_percentage) / 2 AS avg_tpp_over_two_seasons
FROM nba_data_2023_2024 nd2324
LEFT JOIN nba_data_2024_2025 nd2425
ON nd2324.player_name = nd2425.player_name
WHERE nd2324.player_rank_per_season IS NOT NULL and nd2425.player_rank_per_season IS NOT NULL
GROUP BY nd2324.player_name, nd2324.team, nd2324.two_pointer_attempts, nd2425.two_pointer_attempts, nd2324.two_pointer_percentage, nd2425.two_pointer_percentage
)
SELECT cotpa.player_name, cotpa.team,
ROUND(cotpa.avg_tpp_over_two_seasons * 100, 2) AS avg_tpp_over_two_seasons
FROM calc_overall_two_pointer_attempts cotpa
CROSS JOIN calc_avg_tpa cat
WHERE cotpa.avg_tpa_over_two_seasons > cat.average_tpa
ORDER BY cotpa.avg_tpp_over_two_seasons DESC
LIMIT 5;
"""

In [255]:
df = query_df(query)

In [256]:
df

        player_name team avg_tpp_over_two_seasons
0    Daniel Gafford  DAL                    74.10
1  Dereck Lively II  DAL                    72.70
2    Daniel Gafford  2TM                    71.35
3        Obi Toppin  IND                    70.05
4    Daniel Gafford  WAS                    69.60

3. top 5 players by three_pointer_percentage that has a three_pointer_attempt greater than the mean three_pointer_attempt

In [273]:
query = """
WITH calc_avg_tpa AS (
SELECT AVG(three_pointer_attempts) AS average_tpa
FROM nba_data
WHERE three_pointer_attempts IS NOT NULL AND three_pointer_attempts > 0
),
calc_overall_threee_pointer_attempts AS(
SELECT nd2324.player_name, nd2324.team,
(nd2324.three_pointer_attempts + nd2425.three_pointer_attempts) / 2 AS avg_tpa_over_two_seasons,
(nd2324.three_pointer_percentage + nd2425.three_pointer_percentage) / 2 AS avg_tpp_over_two_seasons
FROM nba_data_2023_2024 nd2324
LEFT JOIN nba_data_2024_2025 nd2425
ON nd2324.player_name = nd2425.player_name
WHERE nd2324.player_rank_per_season IS NOT NULL and nd2425.player_rank_per_season IS NOT NULL
GROUP BY nd2324.player_name, nd2324.team, nd2324.three_pointer_attempts, nd2425.three_pointer_attempts, nd2324.three_pointer_percentage, nd2425.three_pointer_percentage
)
SELECT cotpa.player_name, cotpa.team,
ROUND(cotpa.avg_tpp_over_two_seasons * 100, 2) AS avg_tpp_over_two_seasons
FROM calc_overall_threee_pointer_attempts cotpa
CROSS JOIN calc_avg_tpa cat
WHERE cotpa.avg_tpa_over_two_seasons > cat.average_tpa
ORDER BY cotpa.avg_tpp_over_two_seasons DESC
LIMIT 5;
"""

In [274]:
df = query_df(query)

In [275]:
df

     player_name team avg_tpp_over_two_seasons
0  Grayson Allen  PHO                    44.35
1   Luke Kennard  MEM                    44.15
2  Aaron Wiggins  OKC                    43.75
3  Norman Powell  LAC                    42.65
4    Mike Conley  MIN                    42.60

4. top 5 players by effective_field_goal_percentage that has a field_goals_attempt greater than the mean field_goals_attempt

In [277]:
query = """
WITH calc_avg_fga AS (
SELECT AVG(field_goals_attempts) AS average_fga
FROM nba_data
WHERE field_goals_attempts IS NOT NULL AND field_goals_attempts > 0
),
calc_overall_field_goals_attempts AS(
SELECT nd2324.player_name, nd2324.team,
(nd2324.field_goals_attempts + nd2425.field_goals_attempts) / 2 AS avg_fga_over_two_seasons,
(nd2324.effective_field_goal_percentage + nd2425.effective_field_goal_percentage) / 2 AS avg_efgp_over_two_seasons
FROM nba_data_2023_2024 nd2324
LEFT JOIN nba_data_2024_2025 nd2425
ON nd2324.player_name = nd2425.player_name
WHERE nd2324.player_rank_per_season IS NOT NULL and nd2425.player_rank_per_season IS NOT NULL
GROUP BY nd2324.player_name, nd2324.team, nd2324.field_goals_attempts, nd2425.field_goals_attempts, nd2324.effective_field_goal_percentage, nd2425.effective_field_goal_percentage
)
SELECT cofga.player_name, cofga.team,
ROUND(cofga.avg_efgp_over_two_seasons * 100, 2) AS avg_efgp_over_two_seasons
FROM calc_overall_field_goals_attempts cofga
CROSS JOIN calc_avg_fga caf
WHERE cofga.avg_fga_over_two_seasons > caf.average_fga
ORDER BY cofga.avg_efgp_over_two_seasons DESC
LIMIT 5;
"""

In [278]:
df = query_df(query)

In [279]:
df

      player_name team avg_efgp_over_two_seasons
0  Daniel Gafford  2TM                     71.35
1  Daniel Gafford  WAS                     69.60
2   Jarrett Allen  CLE                     67.00
3  Walker Kessler  UTA                     66.55
4     Rudy Gobert  MIN                     66.50

5. top 5 players by free_throw_percentage that has a free_throw_attempts greater than the mean free_throw_attempts

In [281]:
query = """
WITH calc_avg_fta AS (
SELECT AVG(free_throw_attempts) AS average_fta
FROM nba_data
WHERE free_throw_attempts IS NOT NULL AND free_throw_attempts > 0
),
calc_overall_free_throw_attempts AS(
SELECT nd2324.player_name, nd2324.team,
(nd2324.free_throw_attempts + nd2425.free_throw_attempts) / 2 AS avg_fta_over_two_seasons,
(nd2324.free_throw_percentage + nd2425.free_throw_percentage) / 2 AS avg_ftp_over_two_seasons
FROM nba_data_2023_2024 nd2324
LEFT JOIN nba_data_2024_2025 nd2425
ON nd2324.player_name = nd2425.player_name
WHERE nd2324.player_rank_per_season IS NOT NULL and nd2425.player_rank_per_season IS NOT NULL
GROUP BY nd2324.player_name, nd2324.team, nd2324.free_throw_attempts, nd2425.free_throw_attempts, nd2324.free_throw_percentage, nd2425.free_throw_percentage
)
SELECT cofta.player_name, cofta.team,
ROUND(cofta.avg_ftp_over_two_seasons * 100, 2) AS avg_ftp_over_two_seasons
FROM calc_overall_free_throw_attempts cofta
CROSS JOIN calc_avg_fta caf
WHERE cofta.avg_fta_over_two_seasons > caf.average_fta
ORDER BY cofta.avg_ftp_over_two_seasons DESC
LIMIT 5;
"""

In [282]:
df = query_df(query)

In [283]:
df

       player_name team avg_ftp_over_two_seasons
0    Stephen Curry  GSW                    92.80
1   Damian Lillard  MIL                    92.05
2    Klay Thompson  GSW                    91.60
3     Kyrie Irving  DAL                    91.05
4  Anfernee Simons  POR                    90.90

5. top 5 players by total_rebound

In [300]:
query = """
SELECT player_name, ROUND(AVG(total_rebound), 2) AS average_rebound
FROM nba_data
GROUP BY player_name
ORDER BY AVG(total_rebound) DESC
LIMIT 5;
"""

In [301]:
df = query_df(query)

In [302]:
df

             player_name average_rebound
0       Domantas Sabonis         1046.00
1           Nikola Jokić          934.00
2            Rudy Gobert          883.50
3  Giannis Antetokounmpo          819.50
4            Ivica Zubac          818.00

6. top 5 players by assist

In [312]:
query = """
SELECT player_name, ROUND(AVG(assist), 2) AS average_assist
FROM nba_data
GROUP BY player_name
ORDER BY AVG(assist) DESC
LIMIT 5;
"""

In [313]:
df = query_df(query)

In [314]:
df

         player_name average_assist
0         Trae Young         731.50
1  Tyrese Haliburton         712.50
2       Nikola Jokić         712.00
3       James Harden         650.50
4       LeBron James         582.00

7. top 5 players by steal

In [315]:
query = """
SELECT player_name, ROUND(AVG(steal), 2) AS average_steal
FROM nba_data
GROUP BY player_name
ORDER BY AVG(steal) DESC
LIMIT 5;
"""

In [316]:
df = query_df(query)

In [317]:
df

                player_name average_steal
0             Dyson Daniels        157.00
1   Shai Gilgeous-Alexander        140.50
2              Nikola Jokić        117.50
3               Alex Caruso        103.50
4  Kentavious Caldwell-Pope         98.50

8. top 5 players by block

In [318]:
query = """
SELECT player_name, ROUND(AVG(block), 2) AS average_block
FROM nba_data
GROUP BY player_name
ORDER BY AVG(block) DESC
LIMIT 5;
"""

In [319]:
df = query_df(query)

In [320]:
df

         player_name average_block
0  Victor Wembanyama        215.00
1        Brook Lopez        168.50
2     Walker Kessler        146.00
3       Myles Turner        144.00
4        Rudy Gobert        133.00

9. top 5 players by turnover

In [327]:
query = """
SELECT player_name, ROUND(AVG(turnover), 2) AS average_turnover
FROM nba_data
GROUP BY player_name
ORDER BY AVG(turnover) DESC
LIMIT 5;
"""

In [328]:
df = query_df(query)

In [329]:
df

       player_name average_turnover
0       Trae Young           295.00
1     James Harden           263.00
2  Cade Cunningham           260.50
3     LeBron James           252.50
4  Anthony Edwards           245.00

10. top 5 players by points

In [330]:
query = """
SELECT player_name, ROUND(AVG(points), 2) AS average_points
FROM nba_data
GROUP BY player_name
ORDER BY AVG(points) DESC
LIMIT 5;
"""

In [331]:
df = query_df(query)

In [332]:
df

               player_name average_points
0  Shai Gilgeous-Alexander        2369.00
1    Giannis Antetokounmpo        2129.00
2          Anthony Edwards        2113.00
3             Nikola Jokić        2078.00
4             Jayson Tatum        1959.50

##### Compare seasonal stats (23-24 season vs 24-25 season)

1. Find top scorer on each team
    * 2023-2024 season
    * 2024-2025 season

In [21]:
query = """
WITH season_23_24_highest_score AS (
WITH calc_point_ranks AS(
SELECT team, player_name, points, 
    RANK() OVER (PARTITION BY team ORDER BY points DESC) AS points_rank
FROM nba_data_2023_2024
GROUP BY team, player_name, points
ORDER BY team, points DESC
)
SELECT team, player_name, points
FROM calc_point_ranks
WHERE points_rank = 1
ORDER BY team
),
season_24_25_highest_score AS (
WITH calc_point_ranks AS(
SELECT team, player_name, points, 
    RANK() OVER (PARTITION BY team ORDER BY points DESC) AS points_rank
FROM nba_data_2024_2025
GROUP BY team, player_name, points
ORDER BY team, points DESC
)
SELECT team, player_name, points
FROM calc_point_ranks
WHERE points_rank = 1
ORDER BY team
)
SELECT COALESCE(s1hs.team, s2hs.team) AS team,
    s1hs.player_name, s1hs.points AS s_23_24_points, s2hs.player_name, s2hs.points AS s_24_25_points
FROM season_23_24_highest_score s1hs
FULL OUTER JOIN season_24_25_highest_score s2hs
ON s1hs.team = s2hs.team AND s1hs.player_name = s2hs.player_name
WHERE COALESCE(s1hs.team, s2hs.team) = 'MEM'
ORDER BY s1hs.team, s1hs.player_name, s2hs.player_name 
"""

In [22]:
df = query_df(query)

In [23]:
df

  team        player_name  s_23_24_points        player_name  s_24_25_points
0  MEM  Jaren Jackson Jr.            1486  Jaren Jackson Jr.            1641

2. Find top three-point shooter on each team
    * 2023-2024 season
    * 2024-2025 season

In [25]:
query = """
WITH season_23_24_highest_tpp AS (
WITH calc_avg_three_point_attempt AS(
SELECT AVG(three_pointer_attempts) as avg_tpa
FROM nba_data_2023_2024
),
calc_three_pointer_percentage_ranks AS(
SELECT team, player_name, three_pointer_percentage, 
    RANK() OVER (PARTITION BY team ORDER BY three_pointer_percentage DESC) AS three_pointer_percentage_rank
FROM nba_data_2023_2024
CROSS JOIN calc_avg_three_point_attempt
WHERE three_pointer_percentage IS NOT NULL AND three_pointer_percentage > 0 AND three_pointer_attempts >= avg_tpa
GROUP BY team, player_name, three_pointer_percentage
ORDER BY team, three_pointer_percentage DESC
)
SELECT team, player_name, three_pointer_percentage
FROM calc_three_pointer_percentage_ranks
WHERE three_pointer_percentage_rank = 1
ORDER BY team
),
season_24_25_highest_tpp AS (
WITH calc_avg_three_point_attempt AS(
SELECT AVG(three_pointer_attempts) as avg_tpa
FROM nba_data_2024_2025
),
calc_three_pointer_percentage_ranks AS(
SELECT team, player_name, three_pointer_percentage, 
    RANK() OVER (PARTITION BY team ORDER BY three_pointer_percentage DESC) AS three_pointer_percentage_rank
FROM nba_data_2024_2025
CROSS JOIN calc_avg_three_point_attempt
WHERE three_pointer_percentage IS NOT NULL AND three_pointer_percentage > 0 AND three_pointer_attempts >= avg_tpa
GROUP BY team, player_name, three_pointer_percentage
ORDER BY team, three_pointer_percentage DESC
)
SELECT team, player_name, three_pointer_percentage
FROM calc_three_pointer_percentage_ranks
WHERE three_pointer_percentage_rank = 1
ORDER BY team
)
SELECT COALESCE(s1htpp.team, s2htpp.team) AS team,
    s1htpp.player_name, s1htpp.three_pointer_percentage AS s_23_24_three_pointer_percentage, s2htpp.player_name, s2htpp.three_pointer_percentage AS s_24_25_three_pointer_percentage
FROM season_23_24_highest_tpp s1htpp
FULL OUTER JOIN season_24_25_highest_tpp s2htpp
ON s1htpp.team = s2htpp.team AND s1htpp.player_name = s2htpp.player_name
WHERE COALESCE(s1htpp.team, s2htpp.team) = 'MEM'
ORDER BY s1htpp.team, s1htpp.player_name, s2htpp.player_name 
"""

In [26]:
df = query_df(query)

In [27]:
df

,team,player_name,s_23_24_three_pointer_percentage,player_name,s_24_25_three_pointer_percentage
0,MEM,Luke Kennard,0.450,Luke Kennard,0.433

3. Find top two-point shooter on each team
    * 2023-2024 season
    * 2024-2025 season

In [28]:
query = """
WITH season_23_24_highest_tpp AS (
WITH calc_avg_two_pointer_attempts AS(
SELECT AVG(two_pointer_attempts) as avg_tpa
FROM nba_data_2023_2024
),
calc_two_pointer_percentage_ranks AS(
SELECT team, player_name, two_pointer_percentage, 
    RANK() OVER (PARTITION BY team ORDER BY two_pointer_percentage DESC) AS two_pointer_percentage_rank
FROM nba_data_2023_2024
CROSS JOIN calc_avg_two_pointer_attempts
WHERE two_pointer_percentage IS NOT NULL AND two_pointer_percentage > 0 AND three_pointer_attempts >= avg_tpa
GROUP BY team, player_name, two_pointer_percentage
ORDER BY team, two_pointer_percentage DESC
)
SELECT team, player_name, two_pointer_percentage
FROM calc_two_pointer_percentage_ranks
WHERE two_pointer_percentage_rank = 1
ORDER BY team
),
season_24_25_highest_tpp AS (
WITH calc_avg_two_pointer_attempts AS(
SELECT AVG(two_pointer_attempts) as avg_tpa
FROM nba_data_2024_2025
),
calc_two_pointer_percentage_ranks AS(
SELECT team, player_name, two_pointer_percentage, 
    RANK() OVER (PARTITION BY team ORDER BY two_pointer_percentage DESC) AS two_pointer_percentage_rank
FROM nba_data_2024_2025
CROSS JOIN calc_avg_two_pointer_attempts
WHERE two_pointer_percentage IS NOT NULL AND two_pointer_percentage > 0 AND three_pointer_attempts >= avg_tpa
GROUP BY team, player_name, two_pointer_percentage
ORDER BY team, two_pointer_percentage DESC
)
SELECT team, player_name, two_pointer_percentage
FROM calc_two_pointer_percentage_ranks
WHERE two_pointer_percentage_rank = 1
ORDER BY team
)
SELECT COALESCE(s1htpp.team, s2htpp.team) AS team,
    s1htpp.player_name, s1htpp.two_pointer_percentage AS s_23_24_two_pointer_percentage, s2htpp.player_name, s2htpp.two_pointer_percentage AS s_24_25_two_pointer_percentage
FROM season_23_24_highest_tpp s1htpp
FULL OUTER JOIN season_24_25_highest_tpp s2htpp
ON s1htpp.team = s2htpp.team AND s1htpp.player_name = s2htpp.player_name
WHERE COALESCE(s1htpp.team, s2htpp.team) = 'MEM'
ORDER BY s1htpp.team, s1htpp.player_name, s2htpp.player_name 
"""

In [29]:
df = query_df(query)

In [30]:
df

,team,player_name,s_23_24_two_pointer_percentage,player_name,s_24_25_two_pointer_percentage
0,MEM,Desmond Bane,0.536,None,None
1,MEM,None,None,Jay Huff,0.724

4. Find top player with highest effective-field-goal on each team
    * 2023-2024 season
    * 2024-2025 season

In [31]:
query = """
WITH season_23_24_high_efg AS (
WITH calc_avg_fga AS(
SELECT AVG(field_goals_attempts) as avg_fga
FROM nba_data_2023_2024
),
calc_efgp_percentage_ranks AS(
SELECT team, player_name, effective_field_goal_percentage, 
    RANK() OVER (PARTITION BY team ORDER BY effective_field_goal_percentage DESC) AS effective_field_goal_percentage_rank
FROM nba_data_2023_2024
CROSS JOIN calc_avg_fga
WHERE effective_field_goal_percentage IS NOT NULL AND effective_field_goal_percentage > 0 AND field_goals_attempts >= avg_fga
GROUP BY team, player_name, effective_field_goal_percentage
ORDER BY team, effective_field_goal_percentage DESC
)
SELECT team, player_name, effective_field_goal_percentage
FROM calc_efgp_percentage_ranks
WHERE effective_field_goal_percentage_rank = 1
ORDER BY team
),
season_24_25_high_efg AS (
WITH calc_avg_fga AS(
SELECT AVG(field_goals_attempts) as avg_fga
FROM nba_data_2024_2025
),
calc_efgp_percentage_ranks AS(
SELECT team, player_name, effective_field_goal_percentage, 
    RANK() OVER (PARTITION BY team ORDER BY effective_field_goal_percentage DESC) AS effective_field_goal_percentage_rank
FROM nba_data_2024_2025
CROSS JOIN calc_avg_fga
WHERE effective_field_goal_percentage IS NOT NULL AND effective_field_goal_percentage > 0 AND field_goals_attempts >= avg_fga
GROUP BY team, player_name, effective_field_goal_percentage
ORDER BY team, effective_field_goal_percentage DESC
)
SELECT team, player_name, effective_field_goal_percentage
FROM calc_efgp_percentage_ranks
WHERE effective_field_goal_percentage_rank = 1
ORDER BY team
)
SELECT COALESCE(s1hefg.team, s2hefg.team) AS team,
    s1hefg.player_name, s1hefg.effective_field_goal_percentage AS s_23_24_ef_goal_percentage, s2hefg.player_name, s2hefg.effective_field_goal_percentage AS s_24_25_ef_goal_percentage
FROM season_23_24_high_efg s1hefg
FULL OUTER JOIN season_24_25_high_efg s2hefg
ON s1hefg.team = s2hefg.team AND s1hefg.player_name = s2hefg.player_name
WHERE COALESCE(s1hefg.team, s2hefg.team) = 'MEM'
ORDER BY s1hefg.team, s1hefg.player_name, s2hefg.player_name 
"""

In [32]:
df = query_df(query)

In [33]:
df

,team,player_name,s_23_24_ef_goal_percentage,player_name,s_24_25_ef_goal_percentage
0,MEM,Desmond Bane,0.552,None,None
1,MEM,None,None,Brandon Clarke,0.622

5. Find top free throw shooter on each team
    * 2023-2024 season
    * 2024-2025 season

In [709]:
query = """
WITH season_23_24_ftp_highest AS (
WITH calc_avg_fga AS(
SELECT AVG(free_throw_attempts) as avg_fta
FROM nba_data_2023_2024
),
calc_ft_percentage_ranks AS(
SELECT team, player_name, free_throw_percentage, 
    RANK() OVER (PARTITION BY team ORDER BY free_throw_percentage DESC) AS free_throw_percentage_rank
FROM nba_data_2023_2024
CROSS JOIN calc_avg_fga
WHERE free_throw_percentage IS NOT NULL AND free_throw_percentage > 0 AND free_throw_attempts >= avg_fta
GROUP BY team, player_name, free_throw_percentage
ORDER BY team, free_throw_percentage DESC
)
SELECT team, player_name, free_throw_percentage
FROM calc_ft_percentage_ranks
WHERE free_throw_percentage_rank = 1
ORDER BY team
),
season_24_25_ftp_highest AS (
WITH calc_avg_fga AS(
SELECT AVG(free_throw_attempts) as avg_fta
FROM nba_data_2024_2025
),
calc_ft_percentage_ranks AS(
SELECT team, player_name, free_throw_percentage, 
    RANK() OVER (PARTITION BY team ORDER BY free_throw_percentage DESC) AS free_throw_percentage_rank
FROM nba_data_2024_2025
CROSS JOIN calc_avg_fga
WHERE free_throw_percentage IS NOT NULL AND free_throw_percentage > 0 AND free_throw_attempts >= avg_fta
GROUP BY team, player_name, free_throw_percentage
ORDER BY team, free_throw_percentage DESC
)
SELECT team, player_name, free_throw_percentage
FROM calc_ft_percentage_ranks
WHERE free_throw_percentage_rank = 1
ORDER BY team
)
SELECT COALESCE(s1ftph.team, s2ftph.team) AS team,
    s1ftph.player_name, s1ftph.free_throw_percentage, s2ftph.player_name, s2ftph.free_throw_percentage
FROM season_23_24_ftp_highest s1ftph
FULL OUTER JOIN season_24_25_ftp_highest s2ftph
ON s1ftph.team = s2ftph.team AND s1ftph.player_name = s2ftph.player_name
WHERE COALESCE(s1ftph.team, s2ftph.team) = 'LAL'
ORDER BY s1ftph.team, s1ftph.player_name, s2ftph.player_name 
"""

In [710]:
df = query_df(query)

In [711]:
df

,team,player_name,free_throw_percentage,player_name,free_throw_percentage
0,LAL,Austin Reaves,0.853,Austin Reaves,0.877

6. Find top player with highest assist on each team
    * 2023-2024 season
    * 2024-2025 season

In [37]:
query = """
WITH season_23_24_highest_assist AS (
WITH calc_assist_ranks AS(
SELECT team, player_name, (assist / games) AS avg_assist_per_game, 
    RANK() OVER (PARTITION BY team ORDER BY (assist / games) DESC) AS assist_rank
FROM nba_data_2023_2024
GROUP BY team, player_name, assist, games
ORDER BY team, assist DESC
)
SELECT team, player_name, avg_assist_per_game
FROM calc_assist_ranks
WHERE assist_rank = 1
ORDER BY team
),
season_24_25_highest_assist AS (
WITH calc_assist_ranks AS(
SELECT team, player_name, (assist / games) AS avg_assist_per_game, 
    RANK() OVER (PARTITION BY team ORDER BY (assist / games) DESC) AS assist_rank
FROM nba_data_2024_2025
GROUP BY team, player_name, assist, games
ORDER BY team, assist DESC
)
SELECT team, player_name, avg_assist_per_game
FROM calc_assist_ranks
WHERE assist_rank = 1
ORDER BY team
)
SELECT COALESCE(s1ha.team, s2ha.team) AS team,
    s1ha.player_name, s1ha.avg_assist_per_game AS s_23_24_avg_assist_per_game, s2ha.player_name, s2ha.avg_assist_per_game AS s_24_25_avg_assist_per_game
FROM season_23_24_highest_assist s1ha
FULL OUTER JOIN season_24_25_highest_assist s2ha
ON s1ha.team = s2ha.team AND s1ha.player_name = s2ha.player_name
WHERE COALESCE(s1ha.team, s2ha.team) = 'MEM'
ORDER BY s1ha.team, s1ha.player_name, s2ha.player_name 
"""

In [38]:
df = query_df(query)

In [39]:
df

,team,player_name,s_23_24_avg_assist_per_game,player_name,s_24_25_avg_assist_per_game
0,MEM,Ja Morant,8,Ja Morant,7

7. Find top players with highest steal on each team
    * 2023-2024 season
    * 2024-2025 season

In [688]:
query = """
WITH season_23_24_highest_steal AS (
WITH calc_steal_ranks AS(
SELECT team, player_name, (steal / games) AS avg_steal_per_game, 
    RANK() OVER (PARTITION BY team ORDER BY (steal / games) DESC) AS steal_rank
FROM nba_data_2023_2024
GROUP BY team, player_name, steal, games
ORDER BY team, steal DESC
)
SELECT team, player_name, avg_steal_per_game
FROM calc_steal_ranks
WHERE steal_rank = 1
ORDER BY team
),
season_24_25_highest_steal AS (
WITH calc_steal_ranks AS(
SELECT team, player_name, (steal / games) AS avg_steal_per_game, 
    RANK() OVER (PARTITION BY team ORDER BY (steal / games) DESC) AS steal_rank
FROM nba_data_2024_2025
GROUP BY team, player_name, steal, games
ORDER BY team, steal DESC
)
SELECT team, player_name, avg_steal_per_game
FROM calc_steal_ranks
WHERE steal_rank = 1
ORDER BY team
)
SELECT COALESCE(s1hs.team, s2hs.team) AS team,
    s1hs.player_name, s1hs.avg_steal_per_game, s2hs.player_name, s2hs.avg_steal_per_game
FROM season_23_24_highest_steal s1hs
FULL OUTER JOIN season_24_25_highest_steal s2hs
ON s1hs.team = s2hs.team AND s1hs.player_name = s2hs.player_name
WHERE COALESCE(s1hs.team, s2hs.team) = 'LAL'
ORDER BY s1hs.team, s1hs.player_name, s2hs.player_name 
"""

In [689]:
df = query_df(query)

In [690]:
df

,team,player_name,avg_steal_per_game,player_name,avg_steal_per_game
0,LAL,Anthony Davis,1.0,Anthony Davis,1.0
1,LAL,Jarred Vanderbilt,1.0,None,NaN
2,LAL,LeBron James,1.0,LeBron James,1.0
3,LAL,None,NaN,Austin Reaves,1.0
4,LAL,None,NaN,Cam Reddish,1.0
5,LAL,None,NaN,Jordan Goodwin,1.0
6,LAL,None,NaN,Luka Dončić,1.0

8. Find top 3 players with highest block on each team
    * 2023-2024 season
    * 2024-2025 season

In [691]:
query = """
WITH season_23_24_highest_block_players AS (
WITH calc_block_ranks AS(
SELECT team, player_name, (block / games) AS avg_block_per_game, 
    RANK() OVER (PARTITION BY team ORDER BY (block / games) DESC) AS block_rank
FROM nba_data_2023_2024
GROUP BY team, player_name, block, games
ORDER BY team, block DESC
)
SELECT team, player_name, avg_block_per_game
FROM calc_block_ranks
WHERE block_rank = 1
ORDER BY team
),
season_24_25_highest_block_players AS (
WITH calc_block_ranks AS(
SELECT team, player_name, (block / games) AS avg_block_per_game, 
    RANK() OVER (PARTITION BY team ORDER BY (block / games) DESC) AS block_rank
FROM nba_data_2024_2025
GROUP BY team, player_name, block, games
ORDER BY team, block DESC
)
SELECT team, player_name, avg_block_per_game
FROM calc_block_ranks
WHERE block_rank = 1
ORDER BY team
)
SELECT COALESCE(s1hbp.team, s2hbp.team) AS team,
    s1hbp.player_name, s1hbp.avg_block_per_game, s2hbp.player_name, s2hbp.avg_block_per_game
FROM season_23_24_highest_block_players s1hbp
FULL OUTER JOIN season_24_25_highest_block_players s2hbp
ON s1hbp.team = s2hbp.team AND s1hbp.player_name = s2hbp.player_name
WHERE COALESCE(s1hbp.team, s2hbp.team) = 'LAL'
ORDER BY s1hbp.team, s1hbp.player_name, s2hbp.player_name
"""

In [692]:
df = query_df(query)

In [693]:
df

  team    player_name  avg_block_per_game    player_name  avg_block_per_game
0  LAL  Anthony Davis                   2  Anthony Davis                   2

9. Find top 3 players with highest turnover on each team
    * 2023-2024 season
    * 2024-2025 season

In [666]:
query = """
WITH season_23_24_highest_turnover_players AS (
WITH calc_avg_mins_played AS(
SELECT AVG(mins_played) AS avg_min_played
FROM nba_data_2023_2024
),
calc_turnover_ranks AS(
SELECT team, player_name, (turnover/games) AS avg_turnovers_per_game, 
    RANK() OVER (PARTITION BY team ORDER BY (turnover/games) DESC) AS turnover_rank
FROM nba_data_2023_2024
CROSS JOIN calc_avg_mins_played
WHERE mins_played >= avg_min_played
GROUP BY team, player_name, turnover, games
ORDER BY team, turnover DESC
)
SELECT team, player_name, avg_turnovers_per_game
FROM calc_turnover_ranks
WHERE turnover_rank = 1
ORDER BY team
),
season_24_25_highest_turnover_players AS (
WITH calc_avg_mins_played AS(
SELECT AVG(mins_played) AS avg_min_played
FROM nba_data_2024_2025
),
calc_turnover_ranks AS(
SELECT team, player_name, (turnover/games) AS avg_turnovers_per_game, 
    RANK() OVER (PARTITION BY team ORDER BY (turnover/games) DESC) AS turnover_rank
FROM nba_data_2024_2025
CROSS JOIN calc_avg_mins_played
WHERE mins_played >= avg_min_played
GROUP BY team, player_name, turnover, games
ORDER BY team, turnover DESC
)
SELECT team, player_name, avg_turnovers_per_game
FROM calc_turnover_ranks
WHERE turnover_rank = 1
ORDER BY team
)
SELECT COALESCE(s1htp.team, s2htp.team) AS team,
    s1htp.player_name, s1htp.avg_turnovers_per_game, s2htp.player_name, s2htp.avg_turnovers_per_game
FROM season_23_24_highest_turnover_players s1htp
FULL OUTER JOIN season_24_25_highest_turnover_players s2htp
ON s1htp.team = s2htp.team AND s1htp.player_name = s2htp.player_name
WHERE COALESCE(s1htp.team, s2htp.team) = 'LAL'
ORDER BY s1htp.team, s1htp.player_name, s2htp.player_name
"""

In [667]:
df = query_df(query)

In [668]:
df

,team,player_name,avg_turnovers_per_game,player_name,avg_turnovers_per_game
0,LAL,LeBron James,3.0,LeBron James,3
1,LAL,None,NaN,Luka Dončić,3

10. Find top player with highest personal_foul on each team
    * 2023-2024 season
    * 2024-2025 season

In [44]:
query = """
WITH season_23_24_foul_trouble_player AS(
WITH calc_personal_foul_ranks AS(
SELECT team, player_name, (personal_foul/games) AS avg_foul_per_game, 
    RANK() OVER (PARTITION BY team ORDER BY (personal_foul/games) DESC) AS foul_rank
FROM nba_data_2023_2024
GROUP BY team, player_name, personal_foul, games
ORDER BY team, personal_foul DESC
)
SELECT team, player_name, avg_foul_per_game
FROM calc_personal_foul_ranks
WHERE foul_rank = 1
ORDER BY team
),
season_24_25_foul_trouble_player AS(
WITH calc_personal_foul_ranks AS(
SELECT team, player_name, (personal_foul/games) AS avg_foul_per_game, 
    RANK() OVER (PARTITION BY team ORDER BY (personal_foul/games) DESC) AS foul_rank
FROM nba_data_2024_2025
GROUP BY team, player_name, personal_foul, games
ORDER BY team, personal_foul DESC
)
SELECT team, player_name, avg_foul_per_game
FROM calc_personal_foul_ranks
WHERE foul_rank = 1
ORDER BY team
)
SELECT COALESCE(s1ft.team, s2ft.team) AS team,
    s1ft.player_name, s1ft.avg_foul_per_game AS s_23_24_foul_per_game, s2ft.player_name, s2ft.avg_foul_per_game AS s_24_25_foul_per_game
FROM season_23_24_foul_trouble_player s1ft
FULL OUTER JOIN season_24_25_foul_trouble_player s2ft
ON s1ft.team = s2ft.team AND s1ft.player_name = s2ft.player_name
WHERE COALESCE(s1ft.team, s2ft.team) = 'MEM'
ORDER BY s1ft.team, s1ft.player_name, s2ft.player_name
"""

In [45]:
df = query_df(query)

In [46]:
df

,team,player_name,s_23_24_foul_per_game,player_name,s_24_25_foul_per_game
0,MEM,Jaren Jackson Jr.,3,Jaren Jackson Jr.,3.0
1,MEM,Timmy Allen,3,None,NaN
2,MEM,Trey Jemison,3,None,NaN

##### Momentum (for each team)

1. field_goals_percentage

In [18]:
query = """
WITH nd2324 AS (
SELECT team, 
    SUM(field_goals) AS total_field_goals,
    ROUND((SUM(field_goals)*1.0 / SUM(field_goals_attempts)) * 100, 2) AS avg_field_goal_percent, 
    ROUND((SUM(three_pointer)*1.0 / SUM(three_pointer_attempts)) * 100 , 2) AS avg_three_point_percent,
    ROUND((SUM(two_pointer)*1.0 / SUM(two_pointer_attempts)) * 100 , 2) AS avg_two_point_percent,
    ROUND(AVG(effective_field_goal_percentage) * 100 , 2) AS avg_effective_fg_percent,
    ROUND((SUM(free_throw)*1.0 / SUM(free_throw_attempts)) * 100 , 2) AS avg_free_throw_percent,
    ROUND(AVG(total_rebound) , 2) AS avg_rebound,
    ROUND(AVG(assist) , 2) AS avg_assist,
    ROUND(AVG(steal) , 2) AS avg_steal,
    ROUND(AVG(turnover) , 2) AS avg_turnover
FROM nba_data_2023_2024
GROUP BY team
),
nd2425 AS(
SELECT team,
    SUM(field_goals) AS total_field_goals,
    ROUND((SUM(field_goals)*1.0 / SUM(field_goals_attempts)) * 100, 2) AS avg_field_goal_percent, 
    ROUND((SUM(three_pointer)*1.0 / SUM(three_pointer_attempts)) * 100 , 2) AS avg_three_point_percent,
    ROUND((SUM(two_pointer)*1.0 / SUM(two_pointer_attempts)) * 100 , 2) AS avg_two_point_percent,
    ROUND(AVG(effective_field_goal_percentage) * 100 , 2) AS avg_effective_fg_percent,
    ROUND((SUM(free_throw)*1.0 / SUM(free_throw_attempts)) * 100 , 2) AS avg_free_throw_percent,
    ROUND(AVG(total_rebound) , 2) AS avg_rebound,
    ROUND(AVG(assist) , 2) AS avg_assist,
    ROUND(AVG(steal) , 2) AS avg_steal,
    ROUND(AVG(turnover) , 2) AS avg_turnover
FROM nba_data_2024_2025
GROUP BY team
)
SELECT nd2324.team, 
    nd2425.total_field_goals - nd2324.total_field_goals AS field_goal_momentum,
    nd2425.avg_field_goal_percent - nd2324.avg_field_goal_percent AS field_goal_perct_momentum,
    nd2425.avg_three_point_percent - nd2324.avg_three_point_percent AS three_point_perct_momentum,
    nd2425.avg_two_point_percent - nd2324.avg_two_point_percent AS two_point_perct_momentum,
    nd2425.avg_effective_fg_percent - nd2324.avg_effective_fg_percent AS effective_fg_perct_momentum,
    nd2425.avg_free_throw_percent - nd2324.avg_free_throw_percent AS free_throw_perct_momentum,
    nd2425.avg_rebound - nd2324.avg_rebound AS rebound_momentum,
    nd2425.avg_assist - nd2324.avg_assist AS assist_momentum,
    nd2425.avg_steal - nd2324.avg_steal AS steal_momentum,
    nd2425.avg_turnover - nd2324.avg_turnover AS turnover_momentum
FROM nd2324
LEFT JOIN nd2425
ON nd2324.team = nd2425.team
ORDER BY field_goal_momentum DESC, assist_momentum DESC
"""

In [19]:
df = query_df(query)

In [20]:
df

,team,field_goal_momentum,field_goal_perct_momentum,three_point_perct_momentum,two_point_perct_momentum,effective_fg_perct_momentum,free_throw_perct_momentum,rebound_momentum,assist_momentum,steal_momentum,turnover_momentum
0,MEM,525,4.45,2.16,5.43,3.17,2.14,78.64,49.59,14.18,23.10
1,2TM,397,0.89,0.14,0.45,0.55,0.14,-1.13,-3.60,-0.44,3.96
2,CLE,227,1.14,1.57,2.03,0.33,1.16,-19.88,-18.01,-1.71,-9.11
3,NYK,168,2.02,0.01,2.69,6.50,1.98,24.06,30.48,8.41,8.99
4,DET,150,1.24,1.41,2.14,0.99,-1.10,60.15,35.75,13.92,16.26
5,DEN,114,1.01,0.15,1.59,-2.44,0.83,6.30,7.47,4.18,8.47
6,POR,98,1.09,-0.33,3.35,-0.06,-2.96,33.89,16.65,7.18,11.53
7,CHI,95,-0.02,0.95,2.32,7.02,1.80,-28.70,-5.46,-7.21,-1.22
8,HOU,59,-0.43,0.14,-1.18,-1.14,-3.55,1.54,-13.38,0.69,0.51
9,MIA,52,-0.03,-0.23,1.09,0.44,-2.70,4.29,2.38,2.43,3.19
10,3TM,27,0.61,2.29,-2.26,-0.82,3.12,40.29,67.93,9.14,26.36
11,ATL,27,0.71,-0.54,1.65,4.84,-2.28,-19.03,0.78,5.63,2.33
12,OKC,7,-1.72,-1.42,-0.83,1.11,-0.61,36.58,14.84,13.03,3.49
13,SAS,-12,0.31,0.94,1.16,-5.19,-0.79,-10.83,-10.64,2.90,-8.14
14,MIN,-19,-1.67,-0.96,-0.19,-3.69,1.20,-6.56,-7.85,-1.35,-1.28
15,SAC,-24,0.13,-0.85,-0.56,-4.94,6.05,-35.39,-29.44,-6.45,-10.01
16,TOR,-52,-1.37,0.05,-2.06,0.97,-0.72,44.27,23.91,7.74,15.65
17,LAC,-64,-0.68,-0.77,-0.49,7.13,-2.77,-11.63,-10.12,3.13,1.50
18,DAL,-92,-0.22,-0.50,-1.73,0.85,1.14,-12.97,-9.48,0.91,0.41
19,MIL,-93,-0.11,1.41,-1.43,-1.40,-2.41,-17.87,-12.75,-0.44,-2.76
20,PHO,-101,-1.51,-0.40,-0.42,1.98,0.18,9.93,13.03,1.92,1.75
21,UTA,-138,-1.26,-0.40,-0.47,-2.61,-5.60,8.72,-1.64,2.18,9.02
22,CHO,-139,-3.01,-1.59,-2.88,-3.00,-0.35,10.22,-4.34,0.86,4.19
23,PHI,-150,-1.03,-2.17,1.28,1.70,-4.53,-17.02,-9.52,0.28,2.10
24,NOP,-152,-3.41,-3.54,-2.99,5.43,-1.77,-37.21,-25.74,-6.16,-5.18
25,BOS,-188,-2.46,-1.96,-0.41,-6.16,-0.71,6.49,2.95,3.40,3.09
26,ORL,-188,-3.15,-3.31,-1.61,-5.49,1.59,9.10,-1.39,5.71,0.34
27,LAL,-224,-1.99,-1.04,-0.47,4.94,0.39,-23.37,-22.64,-2.43,-7.55
28,GSW,-240,-2.57,-1.58,-2.05,-0.60,-1.61,-51.00,-29.70,1.74,-15.40
29,BRK,-248,-1.92,-1.74,-0.71,1.62,3.09,-30.92,-14.14,0.15,-0.68
30,IND,-281,-1.94,-0.59,-2.14,2.31,0.68,1.14,-5.64,2.87,-0.23
31,WAS,-290,-3.16,-1.33,-2.92,-1.10,1.41,8.96,-9.58,0.00,4.67

##### Momentum analysis (for specific players we're interested in)

1. basic stats

In [88]:
query = """
WITH nd2324_player_stats AS (
SELECT player_name,
    STRING_AGG(DISTINCT team, ', ') AS teams_2324,
    SUM(games) AS games_played,
    SUM(games_started) AS total_games_started, 
    ROUND(AVG(mins_played) / SUM(games), 2) AS avg_mins_played, 
    ROUND(AVG(field_goals_attempts) / SUM(games)) AS avg_field_goals_attempts_per_game,
    ROUND(AVG(field_goals_percentage) * 100, 2) AS field_goal_percentange,
    ROUND(AVG(three_pointer_attempts) / SUM(games)) AS avg_three_pointer_attempts_per_game,
    ROUND(AVG(three_pointer_percentage) * 100, 2) AS three_pointer_percentange,
    ROUND(AVG(two_pointer_attempts) / SUM(games)) AS avg_two_pointer_attempts_per_game,
    ROUND(AVG(two_pointer_percentage) * 100, 2) AS two_pointer_percentange,
    ROUND(AVG(effective_field_goal_percentage) * 100, 2) AS effective_fg_percentange,
    ROUND(AVG(free_throw_attempts) / SUM(games)) AS avg_free_throw_attempts_per_game,
    ROUND(AVG(free_throw_percentage) * 100, 2) AS free_throw_percentange,
    ROUND(AVG(offensive_rebound) / SUM(games), 2) AS avg_off_rebounds_per_game, 
    ROUND(AVG(defensive_rebound) / SUM(games), 2) AS avg_def_rebounds_per_game, 
    ROUND(AVG(total_rebound) / SUM(games), 2) AS avg_total_rebounds_per_game, 
    ROUND(AVG(assist) / SUM(games), 2) AS avg_assist_per_game, 
    ROUND(AVG(steal) / SUM(games), 2) AS avg_steal_per_game, 
    ROUND(AVG(block) / SUM(games), 2) AS avg_block_per_game, 
    ROUND(AVG(turnover) / SUM(games), 2) AS avg_turnover_per_game, 
    ROUND(AVG(points) / SUM(games), 2) AS avg_points_per_game
FROM nba_data_2023_2024
WHERE player_name = 'Jaren Jackson Jr.' OR  player_name = 'Jay Huff' OR player_name = 'Luke Kennard' OR player_name = 'Brandon Clarke' OR player_name = 'Ja Morant'
    AND team != '2TM' AND team != '3TM'
GROUP BY player_name
),
nd2425_player_stats AS (
SELECT player_name, 
    STRING_AGG(DISTINCT team, ', ') AS teams_2425,
    SUM(games) AS games_played,
    SUM(games_started) AS total_games_started, 
    ROUND(AVG(mins_played) / SUM(games), 2) AS avg_mins_played, 
    ROUND(AVG(field_goals_attempts) / SUM(games)) AS avg_field_goals_attempts_per_game,
    ROUND(AVG(field_goals_percentage) * 100, 2) AS field_goal_percentange,
    ROUND(AVG(three_pointer_attempts) / SUM(games)) AS avg_three_pointer_attempts_per_game,
    ROUND(AVG(three_pointer_percentage) * 100, 2) AS three_pointer_percentange,
    ROUND(AVG(two_pointer_attempts) / SUM(games)) AS avg_two_pointer_attempts_per_game,
    ROUND(AVG(two_pointer_percentage) * 100, 2) AS two_pointer_percentange,
    ROUND(AVG(effective_field_goal_percentage) * 100, 2) AS effective_fg_percentange,
    ROUND(AVG(free_throw_attempts) / SUM(games)) AS avg_free_throw_attempts_per_game,
    ROUND(AVG(free_throw_percentage) * 100, 2) AS free_throw_percentange,
    ROUND(AVG(offensive_rebound) / SUM(games), 2) AS avg_off_rebounds_per_game, 
    ROUND(AVG(defensive_rebound) / SUM(games), 2) AS avg_def_rebounds_per_game, 
    ROUND(AVG(total_rebound) / SUM(games), 2) AS avg_total_rebounds_per_game, 
    ROUND(AVG(assist) / SUM(games), 2) AS avg_assist_per_game, 
    ROUND(AVG(steal) / SUM(games), 2) AS avg_steal_per_game, 
    ROUND(AVG(block) / SUM(games), 2) AS avg_block_per_game, 
    ROUND(AVG(turnover) / SUM(games), 2) AS avg_turnover_per_game, 
    ROUND(AVG(points) / SUM(games), 2) AS avg_points_per_game
FROM nba_data_2024_2025
WHERE player_name = 'Jaren Jackson Jr.' OR  player_name = 'Jay Huff' OR player_name = 'Luke Kennard' OR player_name = 'Brandon Clarke' OR player_name = 'Ja Morant'
    AND team != '2TM' AND team != '3TM'
GROUP BY player_name
) 
SELECT COALESCE(nd2324.player_name, nd2425.player_name) AS player,
    nd2324.teams_2324 AS s2324team,
    nd2425.teams_2425 AS s2425team,
    /*COALESCE(nd2425.games_played, 0) - COALESCE(nd2324.games_played, 0) AS games_played,
    COALESCE(nd2425.total_games_started, 0) - COALESCE(nd2324.total_games_started, 0) AS started,
    COALESCE(nd2425.avg_mins_played, 0) - COALESCE(nd2324.avg_mins_played, 0) AS mins,
    COALESCE(nd2425.avg_field_goals_attempts_per_game, 0) - COALESCE(nd2324.avg_field_goals_attempts_per_game, 0) AS fg_atmpts,
    COALESCE(nd2425.field_goal_percentange, 0) - COALESCE(nd2324.field_goal_percentange, 0) AS field_goal_perct,
    COALESCE(nd2425.avg_three_pointer_attempts_per_game, 0) - COALESCE(nd2324.avg_three_pointer_attempts_per_game, 0) AS three_p_atmpts,
    COALESCE(nd2425.three_pointer_percentange, 0) - COALESCE(nd2324.three_pointer_percentange, 0) AS three_p_perct,
    COALESCE(nd2425.avg_two_pointer_attempts_per_game, 0) - COALESCE(nd2324.avg_two_pointer_attempts_per_game, 0) AS two_p_atmpts,
    COALESCE(nd2425.two_pointer_percentange, 0) - COALESCE(nd2324.two_pointer_percentange, 0) AS two_p_perct,
    COALESCE(nd2425.effective_fg_percentange, 0) - COALESCE(nd2324.effective_fg_percentange, 0) AS effc_fg_perct,
    COALESCE(nd2425.avg_free_throw_attempts_per_game, 0) - COALESCE(nd2324.avg_free_throw_attempts_per_game, 0) AS ft_atmpts,
    COALESCE(nd2425.free_throw_percentange, 0) - COALESCE(nd2324.free_throw_percentange, 0) AS ft_perct,*/
    COALESCE(nd2425.avg_off_rebounds_per_game, 0) - COALESCE(nd2324.avg_off_rebounds_per_game, 0) AS off_rb,
    COALESCE(nd2425.avg_def_rebounds_per_game, 0) - COALESCE(nd2324.avg_def_rebounds_per_game, 0) AS def_rb,
    COALESCE(nd2425.avg_total_rebounds_per_game, 0) - COALESCE(nd2324.avg_total_rebounds_per_game, 0) AS tol_rb,
    COALESCE(nd2425.avg_assist_per_game, 0) - COALESCE(nd2324.avg_assist_per_game, 0) AS assist,
    COALESCE(nd2425.avg_steal_per_game, 0) - COALESCE(nd2324.avg_steal_per_game, 0) AS steal,
    COALESCE(nd2425.avg_block_per_game, 0) - COALESCE(nd2324.avg_block_per_game, 0) AS block,
    COALESCE(nd2425.avg_turnover_per_game, 0) - COALESCE(nd2324.avg_turnover_per_game, 0) AS turnover,
    COALESCE(nd2425.avg_points_per_game, 0) - COALESCE(nd2324.avg_points_per_game, 0) AS points_per_game
FROM nd2324_player_stats nd2324
INNER JOIN nd2425_player_stats nd2425
ON nd2324.player_name = nd2425.player_name
"""

In [89]:
df = query_df(query)

In [90]:
df

,player,s2324team,s2425team,off_rb,def_rb,tol_rb,assist,steal,block,turnover,points_per_game
0,Brandon Clarke,MEM,MEM,-0.19,-0.06,-0.24,-0.47,-0.02,-0.44,0.14,-2.99
1,Ja Morant,MEM,MEM,0.01,-1.47,-1.46,-0.83,0.44,-0.32,0.70,-1.93
2,Jaren Jackson Jr.,MEM,MEM,-0.06,0.17,0.11,-0.33,0.03,-0.08,-0.35,-0.34
3,Jay Huff,DEN,MEM,0.37,1.10,1.47,0.49,0.15,0.73,0.48,5.71
4,Luke Kennard,MEM,MEM,0.29,-0.37,-0.08,-0.18,0.26,0.03,-0.27,-2.14

2. position change but on the same team stats momentum

In [962]:
query = """
WITH player_diff_pos AS (
SELECT nd2324.player_name, nd2324.team, nd2324.pos AS pos_2324, nd2425.pos AS pos_2425
FROM nba_data_2023_2024 nd2324
LEFT JOIN nba_data_2024_2025 nd2425
ON nd2324.player_name = nd2425.player_name
WHERE nd2324.pos != nd2425.pos 
AND nd2324.team = nd2425.team 
AND nd2324.team != '2TM' AND nd2324.team != '3TM'
AND nd2425.team != '2TM' AND nd2425.team != '3TM'
),
season_2324_stats AS (
SELECT nd2324.player_name, nd2324.team, nd2324.pos, 
    nd2324.games_started AS s2324_games_started,
    nd2324.field_goals_attempts AS s2324_fga,
    nd2324.three_pointer_attempts AS s2324_three_pa,
    nd2324.two_pointer_attempts AS s2324_two_pa,
    nd2324.free_throw_attempts AS s2324_fta,
    nd2324.total_rebound AS s2324_rb,
    nd2324.assist AS s2324_ast,
    nd2324.turnover AS s2324_tno,
    nd2324.personal_foul AS s2324_pf,
    nd2324.points AS s2324_points
FROM player_diff_pos pdp
LEFT JOIN nba_data_2023_2024 nd2324
ON nd2324.player_name = pdp.player_name AND nd2324.team = pdp.team AND nd2324.pos = pdp.pos_2324
),
season_2425_stats AS (
SELECT nd2425.player_name, nd2425.team, nd2425.pos, 
    nd2425.games_started AS s2425_games_started,
    nd2425.field_goals_attempts AS s2425_fga,
    nd2425.three_pointer_attempts AS s2425_three_pa,
    nd2425.two_pointer_attempts AS s2425_two_pa,
    nd2425.free_throw_attempts AS s2425_fta,
    nd2425.total_rebound AS s2425_rb,
    nd2425.assist AS s2425_ast,
    nd2425.turnover AS s2425_tno,
    nd2425.personal_foul AS s2425_pf,
    nd2425.points AS s2425_points
FROM player_diff_pos pdp
LEFT JOIN nba_data_2024_2025 nd2425
ON nd2425.player_name = pdp.player_name AND nd2425.team = pdp.team AND nd2425.pos = pdp.pos_2425
)
SELECT s2324s.player_name, s2324s.team, s2324s.pos AS position1, s2425s.pos AS position2,
    s2324s.s2324_games_started - s2425s.s2425_games_started AS games_started,
    s2324s.s2324_fga - s2425s.s2425_fga AS fg,
    s2324s.s2324_three_pa - s2425s.s2425_three_pa AS three_pa,
    s2324s.s2324_two_pa - s2425s.s2425_two_pa AS two_pa,
    s2324s.s2324_fta - s2425s.s2425_fta AS fta,
    s2324s.s2324_rb - s2425s.s2425_rb AS rb,
    s2324s.s2324_ast - s2425s.s2425_ast AS ast,
    s2324s.s2324_tno - s2425s.s2425_tno AS tno,
    s2324s.s2324_pf - s2425s.s2425_pf AS pf,
    s2324s.s2324_points - s2425s.s2425_points AS points
FROM season_2324_stats s2324s
LEFT JOIN season_2425_stats s2425s
ON s2324s.player_name = s2425s.player_name AND s2324s.team = s2425s.team 
"""

# WHERE player_name = 'LeBron James'
# LeBron James

In [963]:
df = query_df(query)

In [ ]:
df
# position 1 vs position 2 momentum

,player_name,team,position1,position2,games_started,fg,three_pa,two_pa,fta,rb,ast,tno,pf,points
0,Devin Booker,PHO,PG,SG,-7,-115,-133,18,-26,3,-57,-42,8,-82
1,LeBron James,LAL,PF,SF,1,-1,-33,32,73,-28,14,-15,-21,112
2,Coby White,CHI,PG,SG,5,88,-28,116,-47,85,75,-11,32,0
3,Miles Bridges,CHO,SF,PF,3,121,0,121,-43,24,-17,2,25,149
4,Jalen Williams,OKC,PF,SG,2,-175,-99,-76,-78,-87,-32,-27,17,-135
5,Scottie Barnes,TOR,SG,PF,-5,-121,16,-137,-51,-8,-15,-20,5,-61
6,Keegan Murray,SAC,SF,PF,1,155,62,93,52,-87,20,4,19,230
7,RJ Barrett,TOR,SG,SF,-26,-490,-186,-304,-144,-162,-184,-86,-53,-527
8,Naz Reid,MIN,PF,C,-3,-72,-54,-18,5,-57,-75,3,-17,-48
9,Caris LeVert,CLE,SG,SF,7,522,184,338,118,173,206,66,73,564
10,Jalen Suggs,ORL,SG,PG,40,233,143,90,46,88,76,30,107,376
11,Daniel Gafford,DAL,PF,C,-10,-217,0,-217,-140,-187,-34,-38,-72,-377
12,Josh Hart,NYK,SF,SG,-35,-91,6,-97,-90,-62,-122,-40,-30,-290
13,Jaden McDaniels,MIN,SF,PF,-11,-206,-48,-158,-49,-246,-62,-8,-6,-243
14,OG Anunoby,NYK,SF,PF,-51,-771,-356,-415,-183,-256,-129,-64,-115,-1007
15,Sam Hauser,BOS,SF,PF,-6,84,66,18,8,52,18,9,12,107
16,Malaki Branham,SAS,PG,SG,29,438,184,254,30,97,118,57,65,455
17,Isaac Okoro,CLE,SF,SG,20,213,64,149,91,76,64,31,36,310
18,Andrew Nembhard,IND,PG,SG,-18,-17,-4,-13,-80,-75,-46,-11,-6,-27
19,Precious Achiuwa,NYK,PF,C,8,-28,14,-42,1,34,-2,9,22,-7
20,Miles McBride,NYK,PG,SG,4,-93,-46,-47,-14,-61,-73,-11,0,-49
21,Trayce Jackson-Davis,GSW,PF,C,-21,30,-2,32,30,30,-22,4,35,133
22,Isaiah Stewart,DET,PF,C,41,67,122,-55,-2,-94,-50,-2,-84,68
23,Zach LaVine,CHI,SG,SF,-19,-334,-136,-198,-79,-73,-91,-69,-7,-520
24,Amir Coffey,LAC,SF,SG,0,-158,-63,-95,-58,-13,-1,-12,-18,-233
25,Pat Connaughton,MIL,SF,SG,2,170,157,13,27,130,91,25,54,212
26,Haywood Highsmith,MIA,PF,SF,-16,-62,-41,-21,-7,-42,-42,-20,-47,-73
27,Matisse Thybulle,POR,SF,SG,14,229,183,46,14,84,62,27,79,242
28,Xavier Tillman Sr.,BOS,PF,C,0,13,-4,17,3,11,13,-9,-3,46
29,Jaylin Williams,OKC,C,PF,-8,7,-9,16,11,-28,-10,-1,19,-2
30,Jared Butler,WAS,SG,PG,0,25,37,-12,-9,17,44,21,18,31
31,John Konchar,MEM,SF,SG,19,117,58,59,17,106,68,30,44,123
32,Julian Strawther,DEN,SF,SG,-4,-264,-131,-133,-59,-81,-36,-34,-97,-361
33,KJ Martin,PHI,SF,PF,-5,72,2,70,10,56,31,18,35,60
34,Maxi Kleber,DAL,C,PF,3,50,43,7,26,48,25,5,13,88
35,Sandro Mamukelashvili,SAS,C,PF,5,-126,-97,-29,-24,-40,1,-7,-25,-195
36,Ricky Council IV,PHI,SG,SF,-12,-351,-181,-170,-82,-168,-81,-47,-50,-359
37,Ousmane Dieng,OKC,PF,C,-1,-9,-1,-8,0,-30,6,1,-11,-9
38,Micah Potter,UTA,PF,C,-10,-95,-77,-18,-12,-121,-25,-26,-36,-109
39,Adama Sanogo,CHI,PF,C,0,20,0,20,12,30,-1,4,4,28
40,JD Davison,BOS,SG,PG,0,-22,-11,-11,-3,-3,-3,-11,2,-17
41,Jordan Walsh,BOS,SF,PF,0,-68,-46,-22,-10,-49,-14,-14,-19,-67

3. for each position what has changed over the past 2 season in terms of stats

# check inconsistent momemtum and top performance

In [94]:
query = """
SELECT player_rank_per_season AS rank,
    player_name, team, games, games_started AS started,
    mins_played::int, field_goals, field_goals_attempts AS fg_atmpt, field_goals_percentage AS fg_perct,
    three_pointer, three_pointer_attempts AS three_pt_atmpt, three_pointer_percentage AS three_pt_perct, 
    two_pointer, two_pointer_attempts AS two_pt_atmpt, two_pointer_percentage AS two_pt_perct, 
    assist, personal_foul
FROM nba_data
WHERE player_name = 'Jay Huff'
"""

In [95]:
df = query_df(query)

In [96]:
df

,rank,player_name,team,games,started,mins_played,field_goals,fg_atmpt,fg_perct,three_pointer,three_pt_atmpt,three_pt_perct,two_pointer,two_pt_atmpt,two_pt_perct,assist,personal_foul
0,500,Jay Huff,DEN,20,0,49,9,15,0.600,3,9,0.333,6,6,1.000,2,9
1,256,Jay Huff,MEM,64,2,748,157,305,0.515,81,200,0.405,76,105,0.724,38,78

### closing case find the best matched player

In [129]:
query = """
WITH player_stats AS (
SELECT player_rank_per_season AS rank,
    player_name, pos,
    ROUND(points / games, 2) AS pts_per_game,
    field_goals, field_goals_attempts AS fg_atmpt, field_goals_percentage AS fg_perct,
    three_pointer, three_pointer_attempts AS three_pt_atmpt, three_pointer_percentage AS three_pt_perct, 
    two_pointer, two_pointer_attempts AS two_pt_atmpt, two_pointer_percentage AS two_pt_perct, 
    assist, personal_foul
FROM nba_data_2024_2025
WHERE player_name = 'Jaren Jackson Jr.' OR  player_name = 'Jay Huff' OR player_name = 'Luke Kennard' OR player_name = 'Brandon Clarke' OR player_name = 'Ja Morant'
),
each_stat_rank AS (
SELECT rank, player_name, pos,
    RANK() OVER (ORDER BY (pts_per_game) ASC) AS pts_per_game_rk,
    RANK() OVER (ORDER BY (fg_perct) ASC) AS fg_perct_rk,
    RANK() OVER (ORDER BY (three_pt_perct) ASC) AS three_pt_perct_rk,
    RANK() OVER (ORDER BY (two_pt_perct) ASC) AS two_pt_perct_rk,
    RANK() OVER (ORDER BY (assist) ASC) AS assist_rk,
    RANK() OVER (ORDER BY (personal_foul) ASC) AS personal_foul_rk
FROM player_stats
)
SELECT rank, player_name, pos, pts_per_game_rk, fg_perct_rk, three_pt_perct_rk, two_pt_perct_rk, assist_rk, personal_foul_rk,
    pts_per_game_rk + fg_perct_rk + three_pt_perct_rk + two_pt_perct_rk + assist_rk + personal_foul_rk AS total_score
FROM each_stat_rank
ORDER BY total_score DESC
"""

In [130]:
df = query_df(query)

In [131]:
df

,rank,player_name,pos,pts_per_game_rk,fg_perct_rk,three_pt_perct_rk,two_pt_perct_rk,assist_rk,personal_foul_rk,total_score
0,20,Jaren Jackson Jr.,C,4,3,3,2,3,5,20
1,218,Brandon Clarke,PF,2,5,1,4,2,4,18
2,256,Jay Huff,C,1,4,4,5,1,2,17
3,200,Luke Kennard,SG,2,2,5,3,4,1,17
4,62,Ja Morant,PG,5,1,2,1,5,3,17