### load in the csv data as df first

In [7]:
import pandas as pd

df_2024_2025 = pd.read_csv("nba_2024_to_2025_season_per_player_data.csv")
df_2023_2024 = pd.read_csv("nba_2023_to_2024_season_per_player_data.csv")
full_data = pd.concat([df_2023_2024, df_2024_2025], ignore_index = True)
full_data

# citation for data:
# https://www.basketball-reference.com/leagues/NBA_2024_totals.html

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,Awards,Player-additional
0,1,Luka Dončić,24,DAL,PG,70,70,2624,804,1652,...,647,686,99,38,282,149,2370,21,MVP-3CPOY-6ASNBA1,doncilu01
1,2,Shai Gilgeous-Alexander,25,OKC,PG,75,75,2553,796,1487,...,415,465,150,67,162,184,2254,0,MVP-2DPOY-7CPOY-3ASNBA1,gilgesh01
2,3,Giannis Antetokounmpo,29,MIL,PF,73,73,2567,837,1369,...,841,476,87,79,250,210,2222,10,MVP-4DPOY-9CPOY-12ASNBA1,antetgi01
3,4,Jalen Brunson,27,NYK,PG,77,77,2726,790,1648,...,278,519,70,13,186,144,2212,0,MVP-5CPOY-5ASNBA2,brunsja01
4,5,Nikola Jokić,28,DEN,C,79,79,2737,822,1411,...,976,708,108,68,237,194,2085,25,MVP-1CPOY-4ASNBA1,jokicni01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,565,Riley Minix,24,SAS,SF,1,0,7,0,1,...,2,0,0,0,0,0,0,0,NaN,minixri01
1466,566,Jahlil Okafor,29,IND,C,1,0,3,0,0,...,1,1,0,0,0,0,0,0,NaN,okafoja01
1467,567,Zyon Pullin,23,MEM,SG,3,0,3,0,1,...,0,0,0,0,0,0,0,0,NaN,pullizy01
1468,568,Isaiah Stevens,24,MIA,PG,3,0,6,0,2,...,2,0,1,0,0,0,0,0,NaN,steveis01
1469,569,Terry Taylor,25,SAC,PF,3,0,6,0,1,...,1,2,0,0,0,0,0,0,NaN,taylote01

### Connect to sql, create table, load the dataframe in the created table with StringIO.

In [8]:
import psycopg
import pandas as pd

In [ ]:
# enter own port, dbname, password
conninfo = "host=localhost port=#### dbname=######### user=postgres password=########"
conn = psycopg.connect(conninfo)
cur = conn.cursor()

In [11]:
def execute_sql(sql, params=None):
    """
    For creating tables, inserting into tables.
    """
    with psycopg.connect(conninfo) as conn:
        with conn.cursor() as cur:
            cur.execute(sql, params)
        conn.commit()

In [12]:
def query_df(sql, params=None):
    """
    For running queries. Returns pandas dataframe of query ouput.
    """
    with psycopg.connect(conninfo) as conn:
        with conn.cursor() as cur:
            cur.execute(sql, params)
            cols = [d.name for d in cur.description]
            return pd.DataFrame(cur.fetchall(), columns=cols)

In [137]:
full_data.columns

Index(['player_rank_per_season', 'player_name', 'age', 'team', 'pos', 'games',
       'games_started', 'mins_played', 'field_goals', 'field_goals_attempts',
       'field_goals_percentage', 'three_pointer', 'three_pointer_attempts',
       'three_pointer_percentage', 'two_pointer', 'two_pointer_attempts',
       'two_pointer_percentage', 'effective_field_goal_percentagefree_throw',
       'free_throw_attempts', 'free_throw_percentage', 'offensive_rebound',
       'defensive_rebound', 'total_rebound', 'assist', 'steal', 'block',
       'turnover', 'personal_foul', 'points', 'triple_double', 'awards',
       'player_additional', 'Player-additional'],
      dtype='object')

In [145]:
sql = """
CREATE TABLE nba_data (
player_rank_per_season INT,
player_name TEXT,
age INT,
team TEXT,
pos TEXT,
games INT,
games_started INT,
mins_played NUMERIC(6,2),
field_goals INT,
field_goals_attempts INT,
field_goals_percentage DECIMAL(5,3),
three_pointer INT,
three_pointer_attempts INT,
three_pointer_percentage DECIMAL(5,3),
two_pointer INT,
two_pointer_attempts INT,
two_pointer_percentage DECIMAL(5,3),
effective_field_goal_percentage DECIMAL(5,3),
free_throw INT,
free_throw_attempts INT,
free_throw_percentage DECIMAL(5,3),
offensive_rebound INT,
defensive_rebound INT,
total_rebound INT,
assist INT,
steal INT,
block INT,
turnover INT,
personal_foul INT,
points INT,
triple_double INT,
awards TEXT,
player_additional TEXT
);

CREATE TABLE nba_data_2023_2024 (
player_rank_per_season INT,
player_name TEXT,
age INT,
team TEXT,
pos TEXT,
games INT,
games_started INT,
mins_played NUMERIC(6,2),
field_goals INT,
field_goals_attempts INT,
field_goals_percentage DECIMAL(5,3),
three_pointer INT,
three_pointer_attempts INT,
three_pointer_percentage DECIMAL(5,3),
two_pointer INT,
two_pointer_attempts INT,
two_pointer_percentage DECIMAL(5,3),
effective_field_goal_percentage DECIMAL(5,3),
free_throw INT,
free_throw_attempts INT,
free_throw_percentage DECIMAL(5,3),
offensive_rebound INT,
defensive_rebound INT,
total_rebound INT,
assist INT,
steal INT,
block INT,
turnover INT,
personal_foul INT,
points INT,
triple_double INT,
awards TEXT,
player_additional TEXT
);

CREATE TABLE nba_data_2024_2025 (
player_rank_per_season INT,
player_name TEXT,
age INT,
team TEXT,
pos TEXT,
games INT,
games_started INT,
mins_played NUMERIC(6,2),
field_goals INT,
field_goals_attempts INT,
field_goals_percentage DECIMAL(5,3),
three_pointer INT,
three_pointer_attempts INT,
three_pointer_percentage DECIMAL(5,3),
two_pointer INT,
two_pointer_attempts INT,
two_pointer_percentage DECIMAL(5,3),
effective_field_goal_percentage DECIMAL(5,3),
free_throw INT,
free_throw_attempts INT,
free_throw_percentage DECIMAL(5,3),
offensive_rebound INT,
defensive_rebound INT,
total_rebound INT,
assist INT,
steal INT,
block INT,
turnover INT,
personal_foul INT,
points INT,
triple_double INT,
awards TEXT,
player_additional TEXT
);
"""

In [146]:
# sql = """
# DROP TABLE IF EXISTS nba_data;
# DROP TABLE IF EXISTS nba_data_2023_2024;
# DROP TABLE IF EXISTS nba_data_2024_2025;
# """

In [147]:
execute_sql(sql)

In [148]:
# rename full_data col so it matches with the sql query create table.
sql_table_col_names = ["player_rank_per_season", "player_name", "age", "team", "pos", "games", 
                       "games_started", "mins_played", "field_goals", "field_goals_attempts", "field_goals_percentage",
                       "three_pointer", "three_pointer_attempts", "three_pointer_percentage",
                       "two_pointer", "two_pointer_attempts", "two_pointer_percentage", "effective_field_goal_percentage"
                       "free_throw", "free_throw_attempts", "free_throw_percentage",
                       "offensive_rebound", "defensive_rebound", "total_rebound", 
                       "assist", "steal", "block", "turnover", "personal_foul",
                       "points", "triple_double", "awards", "player_additional"]
full_data = full_data.rename(columns = dict(zip(full_data.columns, sql_table_col_names)))
df_2024_2025 = df_2024_2025.rename(columns = dict(zip(df_2024_2025.columns, sql_table_col_names)))
df_2023_2024 = df_2023_2024.rename(columns = dict(zip(df_2023_2024.columns, sql_table_col_names)))
full_data.head(1)

,player_rank_per_season,player_name,age,team,pos,games,games_started,mins_played,field_goals,field_goals_attempts,...,assist,steal,block,turnover,personal_foul,points,triple_double,awards,player_additional,Player-additional
0,1,Luka Dončić,24,DAL,PG,70,70,2624,804,1652,...,647,686,99,38,282,149,2370,21,MVP-3CPOY-6ASNBA1,doncilu01

In [ ]:
# conn.rollback()

In [151]:
from io import StringIO

full_data = full_data.rename(columns = dict(zip(full_data.columns, sql_table_col_names)))
df_names = [full_data, df_2024_2025, df_2023_2024]
sql_table_names = ["nba_data", "nba_data_2024_2025", "nba_data_2023_2024"]
for i in range(len(df_names)):
    buffer = StringIO()
    df_names[i].to_csv(buffer, index=False, header=True)
    buffer.seek(0)

    with conn.cursor() as cur:
        with cur.copy("COPY " + sql_table_names[i] + "(player_rank_per_season, player_name, age, team, pos, "
                    "games, games_started, mins_played, "
                    "field_goals, field_goals_attempts, field_goals_percentage, "
                    "three_pointer, three_pointer_attempts, three_pointer_percentage, "
                    "two_pointer, two_pointer_attempts, two_pointer_percentage, effective_field_goal_percentage,"
                    "free_throw, free_throw_attempts, free_throw_percentage, "
                    "offensive_rebound, defensive_rebound, total_rebound, "
                    "assist, steal, block, turnover, personal_foul, "
                    "points, triple_double, awards, player_additional) "
                    "FROM STDIN WITH CSV HEADER") as copy:
            copy.write(buffer.getvalue())

    conn.commit()
    print("Data loaded successfully")
    
conn.close()
# citation
# got help from llm to convert dataframe to sql query without having to manually write out the whole data by hand

Data loaded successfully
Data loaded successfully
Data loaded successfully

### Begin Methods

##### Data Exploration: Examine league-wide statistics
Look for top 5 players that played in both 2023-2024 and 2024-2025 season by different stats

1. top 5 players by overall player rank that played in both seasons

In [372]:
query = """
WITH calc_overall_avg_rank AS(
SELECT nd2324.player_name, 
    (nd2324.player_rank_per_season + nd2425.player_rank_per_season) / 2 AS avg_player_rank_over_two_seasons
FROM nba_data_2023_2024 nd2324
LEFT JOIN nba_data_2024_2025 nd2425
ON nd2324.player_name = nd2425.player_name
WHERE nd2324.player_rank_per_season IS NOT NULL and nd2425.player_rank_per_season IS NOT NULL
GROUP BY nd2324.player_name, nd2324.player_rank_per_season, nd2425.player_rank_per_season
)
SELECT coar.player_name, coar.avg_player_rank_over_two_seasons
FROM calc_overall_avg_rank coar
ORDER BY coar.avg_player_rank_over_two_seasons ASC
LIMIT 5;
"""

In [373]:
df = query_df(query)

In [374]:
df

               player_name  avg_player_rank_over_two_seasons
0  Shai Gilgeous-Alexander                                 1
1    Giannis Antetokounmpo                                 3
2             Nikola Jokić                                 4
3          Anthony Edwards                                 4
4             Jayson Tatum                                 6

2. top 5 players by different shooting attempts that has shooting attempts greater than the mean shooting attempt for each shot

In [375]:
shooting_attempts = ['field_goals_attempts', 'two_pointer_attempts', 'three_pointer_attempts', 'field_goals_attempts', 'free_throw_attempts']
shooting_percentage = ['field_goals_percentage', 'two_pointer_percentage', 'three_pointer_percentage', 'effective_field_goal_percentage', 'free_throw_percentage']
attempt_naming = ['avg_fga_over_two_seasons', 'avg_tpa_over_two_seasons', 'avg_tpa_over_two_seasons', 'avg_fga_over_two_seasons', 'avg_fta_over_two_seasons']
percentage_naming = ['avg_fgp_over_two_seasons', 'avg_tpp_over_two_seasons', 'avg_tpp_over_two_seasons', 'avg_efgp_over_two_seasons', 'avg_ftp_over_two_seasons']

In [376]:
for i in range(len(shooting_attempts)):
    query = """
    WITH calc_avg_fga AS (
    SELECT AVG( """ + shooting_attempts[i] + """) AS average_fga
    FROM nba_data
    WHERE """ + shooting_attempts[i] + """ IS NOT NULL AND """ + shooting_attempts[i] + """ > 0
    ),
    calc_overall_field_goals_attempts AS(
    SELECT nd2324.player_name, nd2324.team,
    (nd2324.""" + shooting_attempts[i] + """ + nd2425.""" + shooting_attempts[i] + """) / 2 AS """ + attempt_naming[i] + """,
    (nd2324.""" + shooting_percentage[i] + """ + nd2425.""" + shooting_percentage[i] + """) / 2 AS """ + percentage_naming[i] + """
    FROM nba_data_2023_2024 nd2324
    LEFT JOIN nba_data_2024_2025 nd2425
    ON nd2324.player_name = nd2425.player_name
    WHERE nd2324.player_rank_per_season IS NOT NULL and nd2425.player_rank_per_season IS NOT NULL
    GROUP BY nd2324.player_name, nd2324.team, nd2324.""" + shooting_attempts[i] + """, nd2425.""" + shooting_attempts[i] + """, nd2324.""" + shooting_percentage[i] + """, nd2425.""" + shooting_percentage[i] + """
    )
    SELECT cofga.player_name, cofga.team,
    ROUND(cofga.""" + percentage_naming[i] + """ * 100, 2) AS """ + percentage_naming[i] + """
    FROM calc_overall_field_goals_attempts cofga
    CROSS JOIN calc_avg_fga caf
    WHERE cofga.""" + attempt_naming[i] + """ > caf.average_fga
    ORDER BY cofga.""" + percentage_naming[i] + """ DESC
    LIMIT 5;
    """

    df = query_df(query)
    display(df)

      player_name team avg_fgp_over_two_seasons
0  Daniel Gafford  2TM                    71.35
1  Daniel Gafford  WAS                    69.60
2   Jarrett Allen  CLE                    67.00
3     Rudy Gobert  MIN                    66.50
4  Walker Kessler  UTA                    65.85

        player_name team avg_tpp_over_two_seasons
0    Daniel Gafford  DAL                    74.10
1  Dereck Lively II  DAL                    72.70
2    Daniel Gafford  2TM                    71.35
3        Obi Toppin  IND                    70.05
4    Daniel Gafford  WAS                    69.60

     player_name team avg_tpp_over_two_seasons
0  Grayson Allen  PHO                    44.35
1   Luke Kennard  MEM                    44.15
2  Aaron Wiggins  OKC                    43.75
3  Norman Powell  LAC                    42.65
4    Mike Conley  MIN                    42.60

      player_name team avg_efgp_over_two_seasons
0  Daniel Gafford  2TM                     71.35
1  Daniel Gafford  WAS                     69.60
2   Jarrett Allen  CLE                     67.00
3  Walker Kessler  UTA                     66.55
4     Rudy Gobert  MIN                     66.50

       player_name team avg_ftp_over_two_seasons
0    Stephen Curry  GSW                    92.80
1   Damian Lillard  MIL                    92.05
2    Klay Thompson  GSW                    91.60
3     Kyrie Irving  DAL                    91.05
4  Anfernee Simons  POR                    90.90

3. top 5 players by other none shooting stats

In [377]:
non_shooting_stats = ['total_rebound', 'assist', 'steal', 'block', 'turnover', 'points']

In [378]:
for i in range(len(non_shooting_stats)):
    query = """
    SELECT player_name, ROUND(AVG(""" + non_shooting_stats[i] +"""), 2) AS average_""" + non_shooting_stats[i] +"""
    FROM nba_data
    GROUP BY player_name
    ORDER BY AVG(""" + non_shooting_stats[i] +""") DESC
    LIMIT 5;
    """

    df = query_df(query)
    display(df)

             player_name average_total_rebound
0       Domantas Sabonis               1046.00
1           Nikola Jokić                934.00
2            Rudy Gobert                883.50
3  Giannis Antetokounmpo                819.50
4            Ivica Zubac                818.00

         player_name average_assist
0         Trae Young         731.50
1  Tyrese Haliburton         712.50
2       Nikola Jokić         712.00
3       James Harden         650.50
4       LeBron James         582.00

                player_name average_steal
0             Dyson Daniels        157.00
1   Shai Gilgeous-Alexander        140.50
2              Nikola Jokić        117.50
3               Alex Caruso        103.50
4  Kentavious Caldwell-Pope         98.50

         player_name average_block
0  Victor Wembanyama        215.00
1        Brook Lopez        168.50
2     Walker Kessler        146.00
3       Myles Turner        144.00
4        Rudy Gobert        133.00

       player_name average_turnover
0       Trae Young           295.00
1     James Harden           263.00
2  Cade Cunningham           260.50
3     LeBron James           252.50
4  Anthony Edwards           245.00

               player_name average_points
0  Shai Gilgeous-Alexander        2369.00
1    Giannis Antetokounmpo        2129.00
2          Anthony Edwards        2113.00
3             Nikola Jokić        2078.00
4             Jayson Tatum        1959.50

##### Team Momentum calculation
Aggregate team stats across two season, and compute the momentum in statistics (based on recruiter's needs)

In [379]:
recruters_needs_shooting = ['field_goals', 'three_pointer', 'two_pointer', 'effective_field_goal', 'free_throw']
recruters_needs_non_shooting = ['mins_played', 'field_goals', 'offensive_rebound', 'defensive_rebound', 'total_rebound', 'assist', 'steal', 'turnover']

In [380]:
# shooting stats query
shooting_query = ""
for s in recruters_needs_shooting:
    if s == 'effective_field_goal':
        query_partial = "ROUND(AVG(effective_field_goal_percentage) * 100 , 2) AS avg_effective_field_goal_percent,"
        shooting_query += query_partial
    else:
        query_partial = "ROUND((SUM(" + s + ")*1.0 / SUM(" + s + "_attempts)) * 100, 2) AS avg_" + s + "_percent,"
        shooting_query += query_partial

# non shooting stats query
non_shooting_query = ""
for ns in recruters_needs_non_shooting:
    if ns == 'field_goals':
        query_partial = "SUM(field_goals) AS total_field_goals,"
        non_shooting_query += query_partial
    else:
        query_partial = "ROUND(AVG(" + ns + ") , 2) AS avg_" + ns + ","
        non_shooting_query += query_partial
non_shooting_query = non_shooting_query[:-1]

# combine
seasonal_selected_stat = shooting_query + non_shooting_query
seasonal_selected_stat

########################################################################################################################################

# final momentum select part
# shooting stats query
final_select_part = ""
for s in recruters_needs_shooting:
    if s == 'field_goals':
        query_partial = "nd2425.total_field_goals - nd2324.total_field_goals AS field_goal_momentum,"
        final_select_part += query_partial
    else:
        query_partial = "nd2425.avg_" + s + "_percent - nd2324.avg_" + s + "_percent AS " + s + "_perct_momentum,"
        final_select_part += query_partial

# nonshooting stats query
for ns in recruters_needs_non_shooting:
    if ns == 'field_goals':
        query_partial = "nd2425.total_field_goals - nd2324.total_field_goals AS field_goal_momentum,"
        non_shooting_query += query_partial
    else:
        query_partial = "nd2425.avg_" + ns + " - nd2324.avg_" + ns + " AS " + ns + "_momentum,"
        final_select_part += query_partial
final_select_part = final_select_part[:-1]
final_select_part

'nd2425.total_field_goals - nd2324.total_field_goals AS field_goal_momentum,nd2425.avg_three_pointer_percent - nd2324.avg_three_pointer_percent AS three_pointer_perct_momentum,nd2425.avg_two_pointer_percent - nd2324.avg_two_pointer_percent AS two_pointer_perct_momentum,nd2425.avg_effective_field_goal_percent - nd2324.avg_effective_field_goal_percent AS effective_field_goal_perct_momentum,nd2425.avg_free_throw_percent - nd2324.avg_free_throw_percent AS free_throw_perct_momentum,nd2425.avg_mins_played - nd2324.avg_mins_played AS mins_played_momentum,nd2425.avg_offensive_rebound - nd2324.avg_offensive_rebound AS offensive_rebound_momentum,nd2425.avg_defensive_rebound - nd2324.avg_defensive_rebound AS defensive_rebound_momentum,nd2425.avg_total_rebound - nd2324.avg_total_rebound AS total_rebound_momentum,nd2425.avg_assist - nd2324.avg_assist AS assist_momentum,nd2425.avg_steal - nd2324.avg_steal AS steal_momentum,nd2425.avg_turnover - nd2324.avg_turnover AS turnover_momentum'

In [381]:
print(seasonal_selected_stat)

ROUND((SUM(field_goals)*1.0 / SUM(field_goals_attempts)) * 100, 2) AS avg_field_goals_percent,ROUND((SUM(three_pointer)*1.0 / SUM(three_pointer_attempts)) * 100, 2) AS avg_three_pointer_percent,ROUND((SUM(two_pointer)*1.0 / SUM(two_pointer_attempts)) * 100, 2) AS avg_two_pointer_percent,ROUND(AVG(effective_field_goal_percentage) * 100 , 2) AS avg_effective_field_goal_percent,ROUND((SUM(free_throw)*1.0 / SUM(free_throw_attempts)) * 100, 2) AS avg_free_throw_percent,ROUND(AVG(mins_played) , 2) AS avg_mins_played,SUM(field_goals) AS total_field_goals,ROUND(AVG(offensive_rebound) , 2) AS avg_offensive_rebound,ROUND(AVG(defensive_rebound) , 2) AS avg_defensive_rebound,ROUND(AVG(total_rebound) , 2) AS avg_total_rebound,ROUND(AVG(assist) , 2) AS avg_assist,ROUND(AVG(steal) , 2) AS avg_steal,ROUND(AVG(turnover) , 2) AS avg_turnover

In [382]:
query = """
WITH nd2324 AS (
SELECT team, 
""" + seasonal_selected_stat + """
FROM nba_data_2023_2024
GROUP BY team
),
nd2425 AS(
SELECT team,
""" + seasonal_selected_stat + """
FROM nba_data_2024_2025
GROUP BY team
)
SELECT nd2324.team,
""" + final_select_part + """
FROM nd2324
LEFT JOIN nd2425
ON nd2324.team = nd2425.team
ORDER BY field_goal_momentum DESC, assist_momentum DESC
"""

In [383]:
df = query_df(query)

In [384]:
df

,team,field_goal_momentum,three_pointer_perct_momentum,two_pointer_perct_momentum,effective_field_goal_perct_momentum,free_throw_perct_momentum,mins_played_momentum,offensive_rebound_momentum,defensive_rebound_momentum,total_rebound_momentum,assist_momentum,steal_momentum,turnover_momentum
0,MEM,525,2.16,5.43,3.17,2.14,339.05,23.14,55.51,78.64,49.59,14.18,23.10
1,2TM,397,0.14,0.45,0.55,0.14,-102.49,-0.49,-0.64,-1.13,-3.60,-0.44,3.96
2,CLE,227,1.57,2.03,0.33,1.16,-159.60,-1.16,-18.71,-19.88,-18.01,-1.71,-9.11
3,NYK,168,0.01,2.69,6.50,1.98,187.98,2.42,21.64,24.06,30.48,8.41,8.99
4,DET,150,1.41,2.14,0.99,-1.10,305.96,16.56,43.59,60.15,35.75,13.92,16.26
5,DEN,114,0.15,1.59,-2.44,0.83,8.82,2.24,4.06,6.30,7.47,4.18,8.47
6,POR,98,-0.33,3.35,-0.06,-2.96,137.46,10.54,23.35,33.89,16.65,7.18,11.53
7,CHI,95,0.95,2.32,7.02,1.80,-212.11,-13.39,-15.31,-28.70,-5.46,-7.21,-1.22
8,HOU,59,0.14,-1.18,-1.14,-3.55,-68.93,11.38,-9.83,1.54,-13.38,0.69,0.51
9,MIA,52,-0.23,1.09,0.44,-2.70,8.33,1.52,2.76,4.29,2.38,2.43,3.19
10,3TM,27,2.29,-2.26,-0.82,3.12,310.18,9.14,31.14,40.29,67.93,9.14,26.36
11,ATL,27,-0.54,1.65,4.84,-2.28,-103.05,-7.51,-11.51,-19.03,0.78,5.63,2.33
12,OKC,7,-1.42,-0.83,1.11,-0.61,137.07,13.02,23.56,36.58,14.84,13.03,3.49
13,SAS,-12,0.94,1.16,-5.19,-0.79,-51.98,0.22,-11.04,-10.83,-10.64,2.90,-8.14
14,MIN,-19,-0.96,-0.19,-3.69,1.20,-50.87,4.87,-11.44,-6.56,-7.85,-1.35,-1.28
15,SAC,-24,-0.85,-0.56,-4.94,6.05,-197.54,-8.36,-27.03,-35.39,-29.44,-6.45,-10.01
16,TOR,-52,0.05,-2.06,0.97,-0.72,200.86,15.26,29.01,44.27,23.91,7.74,15.65
17,LAC,-64,-0.77,-0.49,7.13,-2.77,-77.15,-2.57,-9.05,-11.63,-10.12,3.13,1.50
18,DAL,-92,-0.50,-1.73,0.85,1.14,-73.60,-1.73,-11.24,-12.97,-9.48,0.91,0.41
19,MIL,-93,1.41,-1.43,-1.40,-2.41,-84.01,-7.46,-10.41,-17.87,-12.75,-0.44,-2.76
20,PHO,-101,-0.40,-0.42,1.98,0.18,92.41,1.38,8.55,9.93,13.03,1.92,1.75
21,UTA,-138,-0.40,-0.47,-2.61,-5.60,47.20,1.44,7.29,8.72,-1.64,2.18,9.02
22,CHO,-139,-1.59,-2.88,-3.00,-0.35,-27.37,7.73,2.49,10.22,-4.34,0.86,4.19
23,PHI,-150,-2.17,1.28,1.70,-4.53,-46.19,-3.96,-13.06,-17.02,-9.52,0.28,2.10
24,NOP,-152,-3.54,-2.99,5.43,-1.77,-194.91,-2.88,-34.33,-37.21,-25.74,-6.16,-5.18
25,BOS,-188,-1.96,-0.41,-6.16,-0.71,58.09,5.72,0.77,6.49,2.95,3.40,3.09
26,ORL,-188,-3.31,-1.61,-5.49,1.59,61.76,5.93,3.17,9.10,-1.39,5.71,0.34
27,LAL,-224,-1.04,-0.47,4.94,0.39,-123.40,0.81,-24.18,-23.37,-22.64,-2.43,-7.55
28,GSW,-240,-1.58,-2.05,-0.60,-1.61,-243.83,-10.59,-40.40,-51.00,-29.70,1.74,-15.40
29,BRK,-248,-1.74,-0.71,1.62,3.09,-118.97,-7.42,-23.50,-30.92,-14.14,0.15,-0.68
30,IND,-281,-0.59,-2.14,2.31,0.68,6.87,-3.41,4.55,1.14,-5.64,2.87,-0.23
31,WAS,-290,-1.33,-2.92,-1.10,1.41,0.09,4.67,4.29,8.96,-9.58,0.00,4.67

##### Candidate player identification:
filter players within selected teams by performance metrics and ranking

1. Find top scorer on each team
    * 2023-2024 season
    * 2024-2025 season

In [385]:
candidate_players = []

In [386]:
# get best team from df above
best_momentum_team = df['team'][0]

In [387]:
query = """
WITH season_23_24_highest_score AS (
WITH calc_point_ranks AS(
SELECT team, player_name, points, 
    RANK() OVER (PARTITION BY team ORDER BY points DESC) AS points_rank
FROM nba_data_2023_2024
GROUP BY team, player_name, points
ORDER BY team, points DESC
)
SELECT team, player_name, points
FROM calc_point_ranks
WHERE points_rank = 1
ORDER BY team
),
season_24_25_highest_score AS (
WITH calc_point_ranks AS(
SELECT team, player_name, points, 
    RANK() OVER (PARTITION BY team ORDER BY points DESC) AS points_rank
FROM nba_data_2024_2025
GROUP BY team, player_name, points
ORDER BY team, points DESC
)
SELECT team, player_name, points
FROM calc_point_ranks
WHERE points_rank = 1
ORDER BY team
)
SELECT COALESCE(s1hs.team, s2hs.team) AS team,
    s1hs.player_name, s1hs.points AS s_23_24_points, s2hs.player_name, s2hs.points AS s_24_25_points
FROM season_23_24_highest_score s1hs
FULL OUTER JOIN season_24_25_highest_score s2hs
ON s1hs.team = s2hs.team AND s1hs.player_name = s2hs.player_name
WHERE COALESCE(s1hs.team, s2hs.team) = '""" + best_momentum_team + """'
ORDER BY s1hs.team, s1hs.player_name, s2hs.player_name 
"""

In [388]:
df = query_df(query)

In [389]:
df

  team        player_name  s_23_24_points        player_name  s_24_25_points
0  MEM  Jaren Jackson Jr.            1486  Jaren Jackson Jr.            1641

2. Find top shooter on each team for different types of shots and effective field goal
    * 2023-2024 season
    * 2024-2025 season

In [390]:
shooting = ['three_pointer_percentage', 'two_pointer_percentage', 'free_throw_percentage', 'effective_field_goal_percentage']
shooting_attp = ['three_pointer_attempts', 'two_pointer_attempts', 'free_throw_attempts', 'field_goals_attempts']

In [391]:
from decimal import Decimal

In [392]:
for i in range(len(shooting)):
    query = """
    WITH season_23_24_highest_tpp AS (
    WITH calc_avg_""" + shooting_attp[i] + """ AS(
    SELECT AVG(""" + shooting_attp[i] + """) as avg_sta
    FROM nba_data_2023_2024
    ),
    calc_shooting_percentage_ranks AS(
    SELECT team, player_name, """ + shooting[i] + """, 
        RANK() OVER (PARTITION BY team ORDER BY """ + shooting[i] + """ DESC) AS """ + shooting[i] + """_rank
    FROM nba_data_2023_2024
    CROSS JOIN calc_avg_""" + shooting_attp[i] + """
    WHERE """ + shooting[i] + """ IS NOT NULL AND """ + shooting[i] + """ > 0 AND """ + shooting_attp[i] + """ >= avg_sta
    GROUP BY team, player_name, """ + shooting[i] + """
    ORDER BY team, """ + shooting[i] + """ DESC
    )
    SELECT team, player_name, """ + shooting[i] + """
    FROM calc_shooting_percentage_ranks
    WHERE """ + shooting[i] + """_rank = 1
    ORDER BY team
    ),
    season_24_25_highest_tpp AS (
    WITH calc_avg_""" + shooting_attp[i] + """ AS(
    SELECT AVG(""" + shooting_attp[i] + """) as avg_sta
    FROM nba_data_2024_2025
    ),
    calc_shooting_percentage_ranks AS(
    SELECT team, player_name, """ + shooting[i] + """, 
        RANK() OVER (PARTITION BY team ORDER BY """ + shooting[i] + """ DESC) AS """ + shooting[i] + """_rank
    FROM nba_data_2024_2025
    CROSS JOIN calc_avg_""" + shooting_attp[i] + """
    WHERE """ + shooting[i] + """ IS NOT NULL AND """ + shooting[i] + """ > 0 AND """ + shooting_attp[i] + """ >= avg_sta
    GROUP BY team, player_name, """ + shooting[i] + """
    ORDER BY team, """ + shooting[i] + """ DESC
    )
    SELECT team, player_name, """ + shooting[i] + """
    FROM calc_shooting_percentage_ranks
    WHERE """ + shooting[i] + """_rank = 1
    ORDER BY team
    )
    SELECT COALESCE(s1htpp.team, s2htpp.team) AS team,
        s1htpp.player_name AS s1_player_name, s1htpp.""" + shooting[i] + """ AS s_23_24_""" + shooting[i] + """, 
        s2htpp.player_name AS s2_player_name, s2htpp.""" + shooting[i] + """ AS s_24_25_""" + shooting[i] + """
    FROM season_23_24_highest_tpp s1htpp
    FULL OUTER JOIN season_24_25_highest_tpp s2htpp
    ON s1htpp.team = s2htpp.team AND s1htpp.player_name = s2htpp.player_name
    WHERE COALESCE(s1htpp.team, s2htpp.team) = '""" + best_momentum_team + """'
    ORDER BY s1htpp.team, s1htpp.player_name, s2htpp.player_name 
    """

    df = query_df(query)
    display(df)

,team,s1_player_name,s_23_24_three_pointer_percentage,s2_player_name,s_24_25_three_pointer_percentage
0,MEM,Luke Kennard,0.450,Luke Kennard,0.433

,team,s1_player_name,s_23_24_two_pointer_percentage,s2_player_name,s_24_25_two_pointer_percentage
0,MEM,Desmond Bane,0.536,None,None
1,MEM,None,None,Brandon Clarke,0.647

,team,s1_player_name,s_23_24_free_throw_percentage,s2_player_name,s_24_25_free_throw_percentage
0,MEM,Desmond Bane,0.870,Desmond Bane,0.894

,team,s1_player_name,s_23_24_effective_field_goal_percentage,s2_player_name,s_24_25_effective_field_goal_percentage
0,MEM,Desmond Bane,0.552,None,None
1,MEM,None,None,Brandon Clarke,0.622

adding candidate part is done manually (only adding players with better or equilvalent performance compared to the previous season's top player)

The meaning of equivalance should vary by whoever is running the queries

In [393]:
candidate_players.append("Luke Kennard")
candidate_players.append("Brandon Clarke")
candidate_players.append("Desmond Bane")
candidate_players.append("Brandon Clarke")

3. Find top player with highest non shooting stats on each team
    * 2023-2024 season
    * 2024-2025 season

In [394]:
non_shooting_stats_v2 = ['total_rebound', 'assist', 'steal', 'block', 'turnover', 'points', 'personal_foul']

In [395]:
for ns in non_shooting_stats_v2:
    query = """
    WITH season_23_24_highest_""" + ns + """ AS (
    WITH calc_""" + ns + """_ranks AS(
    SELECT team, player_name, (""" + ns + """ / games) AS avg_""" + ns + """_per_game, 
        RANK() OVER (PARTITION BY team ORDER BY (""" + ns + """ / games) DESC) AS """ + ns + """_rank
    FROM nba_data_2023_2024
    GROUP BY team, player_name, """ + ns + """, games
    ORDER BY team, """ + ns + """ DESC
    )
    SELECT team, player_name, avg_""" + ns + """_per_game
    FROM calc_""" + ns + """_ranks
    WHERE """ + ns + """_rank = 1
    ORDER BY team
    ),
    season_24_25_highest_""" + ns + """ AS (
    WITH calc_""" + ns + """_ranks AS(
    SELECT team, player_name, (""" + ns + """ / games) AS avg_""" + ns + """_per_game, 
        RANK() OVER (PARTITION BY team ORDER BY (""" + ns + """ / games) DESC) AS """ + ns + """_rank
    FROM nba_data_2024_2025
    GROUP BY team, player_name, """ + ns + """, games
    ORDER BY team, """ + ns + """ DESC
    )
    SELECT team, player_name, avg_""" + ns + """_per_game
    FROM calc_""" + ns + """_ranks
    WHERE """ + ns + """_rank = 1
    ORDER BY team
    )
    SELECT COALESCE(s1ha.team, s2ha.team) AS team,
        s1ha.player_name AS s1_player_name, s1ha.avg_""" + ns + """_per_game AS s_23_24_avg_""" + ns + """_per_game, 
        s2ha.player_name AS s2_player_name, s2ha.avg_""" + ns + """_per_game AS s_24_25_avg_""" + ns + """_per_game
    FROM season_23_24_highest_""" + ns + """ s1ha
    FULL OUTER JOIN season_24_25_highest_""" + ns + """ s2ha
    ON s1ha.team = s2ha.team AND s1ha.player_name = s2ha.player_name
    WHERE COALESCE(s1ha.team, s2ha.team) = '""" + best_momentum_team + """'
    ORDER BY s1ha.team, s1ha.player_name, s2ha.player_name 
    """

    df = query_df(query)
    display(df)

,team,s1_player_name,s_23_24_avg_total_rebound_per_game,s2_player_name,s_24_25_avg_total_rebound_per_game
0,MEM,Jordan Goodwin,8.0,None,NaN
1,MEM,None,NaN,Zach Edey,8.0

,team,s1_player_name,s_23_24_avg_assist_per_game,s2_player_name,s_24_25_avg_assist_per_game
0,MEM,Ja Morant,8,Ja Morant,7

,team,s1_player_name,s_23_24_avg_steal_per_game,s2_player_name,s_24_25_avg_steal_per_game
0,MEM,Marcus Smart,2.0,Marcus Smart,1
1,MEM,None,NaN,Desmond Bane,1
2,MEM,None,NaN,Ja Morant,1
3,MEM,None,NaN,Jaren Jackson Jr.,1
4,MEM,None,NaN,Scotty Pippen Jr.,1

,team,s1_player_name,s_23_24_avg_block_per_game,s2_player_name,s_24_25_avg_block_per_game
0,MEM,Bismack Biyombo,1.0,None,NaN
1,MEM,Brandon Clarke,1.0,None,NaN
2,MEM,Jaren Jackson Jr.,1.0,Jaren Jackson Jr.,1.0
3,MEM,Trey Jemison,1.0,None,NaN
4,MEM,Xavier Tillman Sr.,1.0,None,NaN
5,MEM,None,NaN,Zach Edey,1.0

,team,s1_player_name,s_23_24_avg_turnover_per_game,s2_player_name,s_24_25_avg_turnover_per_game
0,MEM,Ja Morant,3,Ja Morant,3.0
1,MEM,Marcus Smart,3,None,NaN

,team,s1_player_name,s_23_24_avg_points_per_game,s2_player_name,s_24_25_avg_points_per_game
0,MEM,Ja Morant,25,Ja Morant,23

,team,s1_player_name,s_23_24_avg_personal_foul_per_game,s2_player_name,s_24_25_avg_personal_foul_per_game
0,MEM,Jaren Jackson Jr.,3,Jaren Jackson Jr.,3.0
1,MEM,Timmy Allen,3,None,NaN
2,MEM,Trey Jemison,3,None,NaN

again add these players to the candidate players list

In [396]:
candidate_players.append("Zach Edey")
candidate_players.append("Ja Morant")
candidate_players.append("Desmond Bane")
candidate_players.append("Marcus Smart")
candidate_players.append("Ja Morant")
candidate_players.append("Jaren Jackson Jr.")
candidate_players.append("Scotty Pippen Jr.")
candidate_players.append("Jaren Jackson Jr.")
candidate_players.append("Zach Edey")
candidate_players.append("Ja Morant")
candidate_players.append("Ja Morant")
candidate_players.append("Jaren Jackson Jr.")

In [397]:
cleaned_candidate_players = []
for cp in candidate_players:
    if cp not in cleaned_candidate_players:
        cleaned_candidate_players.append(cp)

cleaned_candidate_players

['Luke Kennard',
 'Brandon Clarke',
 'Desmond Bane',
 'Zach Edey',
 'Ja Morant',
 'Marcus Smart',
 'Jaren Jackson Jr.',
 'Scotty Pippen Jr.']

##### Candidate momentum analysis

In [398]:
print(cleaned_candidate_players)

['Luke Kennard', 'Brandon Clarke', 'Desmond Bane', 'Zach Edey', 'Ja Morant', 'Marcus Smart', 'Jaren Jackson Jr.', 'Scotty Pippen Jr.']

In [399]:
# where piece in the sql query to filter out the players we want to see
player_filtering_query = """player_name = """ 
for i in range(len(cleaned_candidate_players)):
    if i < len(cleaned_candidate_players) - 1:
        player_filtering_query += """'""" + cleaned_candidate_players[i] + """' OR  player_name = """
    else:
        player_filtering_query += """'""" + cleaned_candidate_players[i] + """' AND team != '2TM' AND team != '3TM'"""
    
player_filtering_query

"player_name = 'Luke Kennard' OR  player_name = 'Brandon Clarke' OR  player_name = 'Desmond Bane' OR  player_name = 'Zach Edey' OR  player_name = 'Ja Morant' OR  player_name = 'Marcus Smart' OR  player_name = 'Jaren Jackson Jr.' OR  player_name = 'Scotty Pippen Jr.' AND team != '2TM' AND team != '3TM'"

In [400]:
all_stats = ['games', 'games_started', 'mins_played', 'field_goals_attempts', 'field_goals_percentage', 'three_pointer_attempts', 'three_pointer_percentage', 
             'two_pointer_attempts', 'two_pointer_percentage', 'effective_field_goal_percentage', 'free_throw_attempts', 'free_throw_percentage', 'offensive_rebound', 'defensive_rebound',
             'total_rebound', 'assist', 'steal', 'block', 'turnover', 'points', 'personal_foul']

In [401]:
select_query = ""

for s in all_stats:
    if s == "games" or s == "games_started":
        select_query +=  "SUM(" + s + ") AS " + s + ","
    elif "percentage" in s and s != "effective_field_goal_percentage":
        select_query += "ROUND(AVG(" + s + ") * 100, 2) AS " + s + ","
    elif s == "effective_field_goal_percentage":
        select_query += "ROUND(AVG(effective_field_goal_percentage) * 100, 2) AS effective_field_goal_percentage,"
    else:
        select_query +=  "ROUND(AVG(" + s + ") / SUM(games), 2) AS " + s + ","

select_query = select_query[:-1]
select_query

'SUM(games) AS games,SUM(games_started) AS games_started,ROUND(AVG(mins_played) / SUM(games), 2) AS mins_played,ROUND(AVG(field_goals_attempts) / SUM(games), 2) AS field_goals_attempts,ROUND(AVG(field_goals_percentage) * 100, 2) AS field_goals_percentage,ROUND(AVG(three_pointer_attempts) / SUM(games), 2) AS three_pointer_attempts,ROUND(AVG(three_pointer_percentage) * 100, 2) AS three_pointer_percentage,ROUND(AVG(two_pointer_attempts) / SUM(games), 2) AS two_pointer_attempts,ROUND(AVG(two_pointer_percentage) * 100, 2) AS two_pointer_percentage,ROUND(AVG(effective_field_goal_percentage) * 100, 2) AS effective_field_goal_percentage,ROUND(AVG(free_throw_attempts) / SUM(games), 2) AS free_throw_attempts,ROUND(AVG(free_throw_percentage) * 100, 2) AS free_throw_percentage,ROUND(AVG(offensive_rebound) / SUM(games), 2) AS offensive_rebound,ROUND(AVG(defensive_rebound) / SUM(games), 2) AS defensive_rebound,ROUND(AVG(total_rebound) / SUM(games), 2) AS total_rebound,ROUND(AVG(assist) / SUM(games), 2) AS assist,ROUND(AVG(steal) / SUM(games), 2) AS steal,ROUND(AVG(block) / SUM(games), 2) AS block,ROUND(AVG(turnover) / SUM(games), 2) AS turnover,ROUND(AVG(points) / SUM(games), 2) AS points,ROUND(AVG(personal_foul) / SUM(games), 2) AS personal_foul'

In [402]:
final_select_query = ""

for s in all_stats:
    final_select_query += "COALESCE(nd2425." + s + ", 0) - COALESCE(nd2324." + s + ", 0) AS " + s + ","

final_select_query = final_select_query[:-1]
final_select_query

'COALESCE(nd2425.games, 0) - COALESCE(nd2324.games, 0) AS games,COALESCE(nd2425.games_started, 0) - COALESCE(nd2324.games_started, 0) AS games_started,COALESCE(nd2425.mins_played, 0) - COALESCE(nd2324.mins_played, 0) AS mins_played,COALESCE(nd2425.field_goals_attempts, 0) - COALESCE(nd2324.field_goals_attempts, 0) AS field_goals_attempts,COALESCE(nd2425.field_goals_percentage, 0) - COALESCE(nd2324.field_goals_percentage, 0) AS field_goals_percentage,COALESCE(nd2425.three_pointer_attempts, 0) - COALESCE(nd2324.three_pointer_attempts, 0) AS three_pointer_attempts,COALESCE(nd2425.three_pointer_percentage, 0) - COALESCE(nd2324.three_pointer_percentage, 0) AS three_pointer_percentage,COALESCE(nd2425.two_pointer_attempts, 0) - COALESCE(nd2324.two_pointer_attempts, 0) AS two_pointer_attempts,COALESCE(nd2425.two_pointer_percentage, 0) - COALESCE(nd2324.two_pointer_percentage, 0) AS two_pointer_percentage,COALESCE(nd2425.effective_field_goal_percentage, 0) - COALESCE(nd2324.effective_field_goal_percentage, 0) AS effective_field_goal_percentage,COALESCE(nd2425.free_throw_attempts, 0) - COALESCE(nd2324.free_throw_attempts, 0) AS free_throw_attempts,COALESCE(nd2425.free_throw_percentage, 0) - COALESCE(nd2324.free_throw_percentage, 0) AS free_throw_percentage,COALESCE(nd2425.offensive_rebound, 0) - COALESCE(nd2324.offensive_rebound, 0) AS offensive_rebound,COALESCE(nd2425.defensive_rebound, 0) - COALESCE(nd2324.defensive_rebound, 0) AS defensive_rebound,COALESCE(nd2425.total_rebound, 0) - COALESCE(nd2324.total_rebound, 0) AS total_rebound,COALESCE(nd2425.assist, 0) - COALESCE(nd2324.assist, 0) AS assist,COALESCE(nd2425.steal, 0) - COALESCE(nd2324.steal, 0) AS steal,COALESCE(nd2425.block, 0) - COALESCE(nd2324.block, 0) AS block,COALESCE(nd2425.turnover, 0) - COALESCE(nd2324.turnover, 0) AS turnover,COALESCE(nd2425.points, 0) - COALESCE(nd2324.points, 0) AS points,COALESCE(nd2425.personal_foul, 0) - COALESCE(nd2324.personal_foul, 0) AS personal_foul'

In [403]:
query = """
WITH nd2324_player_stats AS (
SELECT player_name,
    STRING_AGG(DISTINCT team, ', ') AS teams_2324,
    """ + select_query + """
FROM nba_data_2023_2024
WHERE """ + player_filtering_query + """
GROUP BY player_name
),
nd2425_player_stats AS (
SELECT player_name, 
    STRING_AGG(DISTINCT team, ', ') AS teams_2425,
    """ + select_query + """
FROM nba_data_2024_2025
WHERE """ + player_filtering_query + """
GROUP BY player_name
) 
SELECT COALESCE(nd2324.player_name, nd2425.player_name) AS player,
    nd2324.teams_2324 AS s2324team,
    nd2425.teams_2425 AS s2425team,
    """ + final_select_query + """
FROM nd2324_player_stats nd2324
INNER JOIN nd2425_player_stats nd2425
ON nd2324.player_name = nd2425.player_name
"""

In [404]:
df = query_df(query)

In [405]:
df

,player,s2324team,s2425team,games,games_started,mins_played,field_goals_attempts,field_goals_percentage,three_pointer_attempts,three_pointer_percentage,...,free_throw_percentage,offensive_rebound,defensive_rebound,total_rebound,assist,steal,block,turnover,points,personal_foul
0,Brandon Clarke,MEM,MEM,58,17,-3.47,-3.89,6.20,-0.73,-10.80,...,55.80,-0.19,-0.06,-0.24,-0.47,-0.02,-0.44,0.14,-2.99,0.94
1,Desmond Bane,MEM,MEM,27,26,-2.40,-3.73,2.00,-2.51,1.10,...,2.40,0.04,1.61,1.66,-0.13,0.14,-0.11,-0.22,-4.51,-0.48
2,Ja Morant,MEM,MEM,41,41,-4.95,-1.11,-1.70,0.03,3.40,...,1.10,0.01,-1.47,-1.46,-0.83,0.44,-0.32,0.70,-1.93,0.15
3,Jaren Jackson Jr.,MEM,MEM,8,8,-2.36,-1.22,4.40,-0.29,5.50,...,-2.70,-0.06,0.17,0.11,-0.33,0.03,-0.08,-0.35,-0.34,-0.09
4,Luke Kennard,MEM,MEM,26,-11,-2.97,-1.45,3.00,-2.08,-1.70,...,0.60,0.29,-0.37,-0.08,-0.18,0.26,0.03,-0.27,-2.14,-0.09
5,Marcus Smart,MEM,"2TM, MEM, WAS",48,-6,-23.58,-9.33,-3.30,-5.32,4.10,...,-0.80,-0.12,-1.82,-1.94,-3.23,-1.67,-0.16,-2.57,-11.46,-2.13
6,Scotty Pippen Jr.,MEM,MEM,58,5,-3.80,-2.15,-1.30,-0.66,-2.00,...,-3.20,-0.23,0.32,0.09,-0.28,-0.41,-0.10,-0.92,-3.04,-0.29

##### From everything above, we done everything with all the stats avaliable in the dataset, but to demo an example we will be using only a couple stats from this momentum chart.
for instance, if a recuiter is trying to find a player with scoring ability, assist ability, and plays aggresive on the defensive side (high personal foul), we will only be looking at 
stats such as:

 points, field_goals_percentage, three_pointer_percentage, two_pointer_percentage, effective_field_goal_percentage, assist, and personal_fouls.

In [406]:
# meed to redefine players that matches the recruiter's goals
new_candidates = []
# these were the top shooters but removed top free throw shooter
new_candidates.append("Luke Kennard")
new_candidates.append("Brandon Clarke")
new_candidates.append("Brandon Clarke")
# these were players with top assist and personal_fouls.
new_candidates.append("Ja Morant")
new_candidates.append("Jaren Jackson Jr.")


# where piece in the sql query to filter out the players we want to see
player_filtering_query = """player_name = """ 
for i in range(len(new_candidates)):
    if i < len(new_candidates) - 1:
        player_filtering_query += """'""" + new_candidates[i] + """' OR  player_name = """
    else:
        player_filtering_query += """'""" + new_candidates[i] + """' AND team != '2TM' AND team != '3TM'"""
    
player_filtering_query

"player_name = 'Luke Kennard' OR  player_name = 'Brandon Clarke' OR  player_name = 'Brandon Clarke' OR  player_name = 'Ja Morant' OR  player_name = 'Jaren Jackson Jr.' AND team != '2TM' AND team != '3TM'"

In [407]:
stats_needed = ['points', 'field_goals_percentage', 'three_pointer_percentage', 'two_pointer_percentage', 'effective_field_goal_percentage', 'assist', 'personal_foul']

In [408]:
select_query = ""

for s in stats_needed:
    if s == "games" or s == "games_started":
        select_query +=  "SUM(" + s + ") AS " + s + ","
    elif "percentage" in s and s != "effective_field_goal_percentage":
        select_query += "ROUND(AVG(" + s + ") * 100, 2) AS " + s + ","
    elif s == "effective_field_goal_percentage":
        select_query += "ROUND(AVG(effective_field_goal_percentage) * 100, 2) AS effective_field_goal_percentage,"
    else:
        select_query +=  "ROUND(AVG(" + s + ") / SUM(games), 2) AS " + s + ","

select_query = select_query[:-1]
select_query

'ROUND(AVG(points) / SUM(games), 2) AS points,ROUND(AVG(field_goals_percentage) * 100, 2) AS field_goals_percentage,ROUND(AVG(three_pointer_percentage) * 100, 2) AS three_pointer_percentage,ROUND(AVG(two_pointer_percentage) * 100, 2) AS two_pointer_percentage,ROUND(AVG(effective_field_goal_percentage) * 100, 2) AS effective_field_goal_percentage,ROUND(AVG(assist) / SUM(games), 2) AS assist,ROUND(AVG(personal_foul) / SUM(games), 2) AS personal_foul'

In [409]:
final_select_query = ""

for s in stats_needed:
    final_select_query += "COALESCE(nd2425." + s + ", 0) - COALESCE(nd2324." + s + ", 0) AS " + s + ","

final_select_query = final_select_query[:-1]
final_select_query

'COALESCE(nd2425.points, 0) - COALESCE(nd2324.points, 0) AS points,COALESCE(nd2425.field_goals_percentage, 0) - COALESCE(nd2324.field_goals_percentage, 0) AS field_goals_percentage,COALESCE(nd2425.three_pointer_percentage, 0) - COALESCE(nd2324.three_pointer_percentage, 0) AS three_pointer_percentage,COALESCE(nd2425.two_pointer_percentage, 0) - COALESCE(nd2324.two_pointer_percentage, 0) AS two_pointer_percentage,COALESCE(nd2425.effective_field_goal_percentage, 0) - COALESCE(nd2324.effective_field_goal_percentage, 0) AS effective_field_goal_percentage,COALESCE(nd2425.assist, 0) - COALESCE(nd2324.assist, 0) AS assist,COALESCE(nd2425.personal_foul, 0) - COALESCE(nd2324.personal_foul, 0) AS personal_foul'

In [410]:
query = """
WITH nd2324_player_stats AS (
SELECT player_name,
    STRING_AGG(DISTINCT team, ', ') AS teams_2324,
    """ + select_query + """
FROM nba_data_2023_2024
WHERE """ + player_filtering_query + """
GROUP BY player_name
),
nd2425_player_stats AS (
SELECT player_name, 
    STRING_AGG(DISTINCT team, ', ') AS teams_2425,
    """ + select_query + """
FROM nba_data_2024_2025
WHERE """ + player_filtering_query + """
GROUP BY player_name
) 
SELECT COALESCE(nd2324.player_name, nd2425.player_name) AS player,
    nd2324.teams_2324 AS s2324team,
    nd2425.teams_2425 AS s2425team,
    """ + final_select_query + """
FROM nd2324_player_stats nd2324
INNER JOIN nd2425_player_stats nd2425
ON nd2324.player_name = nd2425.player_name
"""

In [411]:
df = query_df(query)

In [412]:
df

,player,s2324team,s2425team,points,field_goals_percentage,three_pointer_percentage,two_pointer_percentage,effective_field_goal_percentage,assist,personal_foul
0,Brandon Clarke,MEM,MEM,-2.99,6.20,-10.80,4.30,5.40,-0.47,0.94
1,Ja Morant,MEM,MEM,-1.93,-1.70,3.40,-3.20,-0.80,-0.83,0.15
2,Jaren Jackson Jr.,MEM,MEM,-0.34,4.40,5.50,4.00,5.40,-0.33,-0.09
3,Luke Kennard,MEM,MEM,-2.14,3.00,-1.70,10.50,-0.80,-0.18,-0.09

#### This is an extra  step needed if there is inconsistency found in player's promised top performance and their momentum
##### check inconsistent momemtum and top performance

Use Jay Huff as an example, since he had high two point shooting performance but has inconsistency in two point shooting percentage momentum
He is not in the candidate list though. We're just using him as an example to find the reasoning that goes behind an inconsistency and to show the full workflow

In [413]:
example_inconsistent_players = ['Jay Huff']

In [414]:
for player in example_inconsistent_players:
    query = """
    SELECT player_rank_per_season AS rank,
        player_name, team, games, games_started AS started,
        mins_played::int, field_goals, field_goals_attempts AS fg_atmpt, field_goals_percentage AS fg_perct,
        three_pointer, three_pointer_attempts AS three_pt_atmpt, three_pointer_percentage AS three_pt_perct, 
        two_pointer, two_pointer_attempts AS two_pt_atmpt, two_pointer_percentage AS two_pt_perct, 
        assist, personal_foul
    FROM nba_data
    WHERE player_name = '""" + player + """'
    """

    df = query_df(query)
    display(df)

,rank,player_name,team,games,started,mins_played,field_goals,fg_atmpt,fg_perct,three_pointer,three_pt_atmpt,three_pt_perct,two_pointer,two_pt_atmpt,two_pt_perct,assist,personal_foul
0,500,Jay Huff,DEN,20,0,49,9,15,0.600,3,9,0.333,6,6,1.000,2,9
1,256,Jay Huff,MEM,64,2,748,157,305,0.515,81,200,0.405,76,105,0.724,38,78

Manual analysis: More playing time = more shooting attempts = reasonable decrease in shooint percentage

#### Candidate Scoring and ranking

In [415]:
stats_needed = ['points', 'field_goals_percentage', 'three_pointer_percentage', 'two_pointer_percentage', 'effective_field_goal_percentage', 'assist', 'personal_foul']
player_stat_query = ""
for sn in stats_needed:
    player_stat_query += sn + ","

player_stat_query = player_stat_query[:-1]
player_stat_query

'points,field_goals_percentage,three_pointer_percentage,two_pointer_percentage,effective_field_goal_percentage,assist,personal_foul'

In [416]:
ranking_query = ""
for sn in stats_needed:
    ranking_query += "RANK() OVER (ORDER BY (" + sn + ") ASC) AS " + sn + "_rk,"

ranking_query = ranking_query[:-1]
ranking_query

'RANK() OVER (ORDER BY (points) ASC) AS points_rk,RANK() OVER (ORDER BY (field_goals_percentage) ASC) AS field_goals_percentage_rk,RANK() OVER (ORDER BY (three_pointer_percentage) ASC) AS three_pointer_percentage_rk,RANK() OVER (ORDER BY (two_pointer_percentage) ASC) AS two_pointer_percentage_rk,RANK() OVER (ORDER BY (effective_field_goal_percentage) ASC) AS effective_field_goal_percentage_rk,RANK() OVER (ORDER BY (assist) ASC) AS assist_rk,RANK() OVER (ORDER BY (personal_foul) ASC) AS personal_foul_rk'

In [417]:
final_select_ind_rank = ""
final_select_add_point = ""
for sn in stats_needed:
    final_select_ind_rank += sn + "_rk, "
    final_select_add_point += sn + "_rk + "

final_select_ind_rank = final_select_ind_rank
final_select_add_point = final_select_add_point[:-3]
final_select_add_point += " AS total_score"

# combine
rank_sel_query = final_select_ind_rank + final_select_add_point
rank_sel_query

'points_rk, field_goals_percentage_rk, three_pointer_percentage_rk, two_pointer_percentage_rk, effective_field_goal_percentage_rk, assist_rk, personal_foul_rk, points_rk + field_goals_percentage_rk + three_pointer_percentage_rk + two_pointer_percentage_rk + effective_field_goal_percentage_rk + assist_rk + personal_foul_rk AS total_score'

In [418]:
query = """
WITH player_stats AS (
SELECT player_rank_per_season AS rank,
    player_name, pos,
    """ + player_stat_query + """
FROM nba_data_2024_2025
WHERE """ + player_filtering_query + """
),
each_stat_rank AS (
SELECT rank, player_name, pos,
    """ + ranking_query + """
FROM player_stats
)
SELECT rank, player_name, pos,
    """ + rank_sel_query + """
FROM each_stat_rank
ORDER BY total_score DESC
"""

In [419]:
df = query_df(query)

In [420]:
df

,rank,player_name,pos,points_rk,field_goals_percentage_rk,three_pointer_percentage_rk,two_pointer_percentage_rk,effective_field_goal_percentage_rk,assist_rk,personal_foul_rk,total_score
0,20,Jaren Jackson Jr.,C,4,3,3,2,2,2,4,20
1,218,Brandon Clarke,PF,1,4,1,4,4,1,3,18
2,200,Luke Kennard,SG,2,2,4,3,3,3,1,18
3,62,Ja Morant,PG,3,1,2,1,1,4,2,14

##### get data for the best matched player

In [421]:
best_matched_player = df['player_name'][0]
best_matched_player

'Jaren Jackson Jr.'

In [422]:
query = """
SELECT player_rank_per_season AS rank, player_name, pos, points, 
    ROUND(free_throw_percentage*100, 2) AS ft_perct, 
    ROUND(three_pointer_percentage*100, 2) AS three_pt_perct, 
    ROUND(two_pointer_percentage*100, 2) AS two_pt_perct, 
    total_rebound, steal, block, assist
FROM nba_data_2024_2025
WHERE player_name = '""" + best_matched_player + """'
"""

In [423]:
df = query_df(query)

In [424]:
df

,rank,player_name,pos,points,ft_perct,three_pt_perct,two_pt_perct,total_rebound,steal,block,assist
0,20,Jaren Jackson Jr.,C,1641,78.10,37.50,54.10,417,92,113,148

#### Extra analysis that could have been done

1. position change but on the same team stats momentum

In [962]:
query = """
WITH player_diff_pos AS (
SELECT nd2324.player_name, nd2324.team, nd2324.pos AS pos_2324, nd2425.pos AS pos_2425
FROM nba_data_2023_2024 nd2324
LEFT JOIN nba_data_2024_2025 nd2425
ON nd2324.player_name = nd2425.player_name
WHERE nd2324.pos != nd2425.pos 
AND nd2324.team = nd2425.team 
AND nd2324.team != '2TM' AND nd2324.team != '3TM'
AND nd2425.team != '2TM' AND nd2425.team != '3TM'
),
season_2324_stats AS (
SELECT nd2324.player_name, nd2324.team, nd2324.pos, 
    nd2324.games_started AS s2324_games_started,
    nd2324.field_goals_attempts AS s2324_fga,
    nd2324.three_pointer_attempts AS s2324_three_pa,
    nd2324.two_pointer_attempts AS s2324_two_pa,
    nd2324.free_throw_attempts AS s2324_fta,
    nd2324.total_rebound AS s2324_rb,
    nd2324.assist AS s2324_ast,
    nd2324.turnover AS s2324_tno,
    nd2324.personal_foul AS s2324_pf,
    nd2324.points AS s2324_points
FROM player_diff_pos pdp
LEFT JOIN nba_data_2023_2024 nd2324
ON nd2324.player_name = pdp.player_name AND nd2324.team = pdp.team AND nd2324.pos = pdp.pos_2324
),
season_2425_stats AS (
SELECT nd2425.player_name, nd2425.team, nd2425.pos, 
    nd2425.games_started AS s2425_games_started,
    nd2425.field_goals_attempts AS s2425_fga,
    nd2425.three_pointer_attempts AS s2425_three_pa,
    nd2425.two_pointer_attempts AS s2425_two_pa,
    nd2425.free_throw_attempts AS s2425_fta,
    nd2425.total_rebound AS s2425_rb,
    nd2425.assist AS s2425_ast,
    nd2425.turnover AS s2425_tno,
    nd2425.personal_foul AS s2425_pf,
    nd2425.points AS s2425_points
FROM player_diff_pos pdp
LEFT JOIN nba_data_2024_2025 nd2425
ON nd2425.player_name = pdp.player_name AND nd2425.team = pdp.team AND nd2425.pos = pdp.pos_2425
)
SELECT s2324s.player_name, s2324s.team, s2324s.pos AS position1, s2425s.pos AS position2,
    s2324s.s2324_games_started - s2425s.s2425_games_started AS games_started,
    s2324s.s2324_fga - s2425s.s2425_fga AS fg,
    s2324s.s2324_three_pa - s2425s.s2425_three_pa AS three_pa,
    s2324s.s2324_two_pa - s2425s.s2425_two_pa AS two_pa,
    s2324s.s2324_fta - s2425s.s2425_fta AS fta,
    s2324s.s2324_rb - s2425s.s2425_rb AS rb,
    s2324s.s2324_ast - s2425s.s2425_ast AS ast,
    s2324s.s2324_tno - s2425s.s2425_tno AS tno,
    s2324s.s2324_pf - s2425s.s2425_pf AS pf,
    s2324s.s2324_points - s2425s.s2425_points AS points
FROM season_2324_stats s2324s
LEFT JOIN season_2425_stats s2425s
ON s2324s.player_name = s2425s.player_name AND s2324s.team = s2425s.team 
"""

# WHERE player_name = 'LeBron James'
# LeBron James

In [963]:
df = query_df(query)

In [ ]:
df
# position 1 vs position 2 momentum

,player_name,team,position1,position2,games_started,fg,three_pa,two_pa,fta,rb,ast,tno,pf,points
0,Devin Booker,PHO,PG,SG,-7,-115,-133,18,-26,3,-57,-42,8,-82
1,LeBron James,LAL,PF,SF,1,-1,-33,32,73,-28,14,-15,-21,112
2,Coby White,CHI,PG,SG,5,88,-28,116,-47,85,75,-11,32,0
3,Miles Bridges,CHO,SF,PF,3,121,0,121,-43,24,-17,2,25,149
4,Jalen Williams,OKC,PF,SG,2,-175,-99,-76,-78,-87,-32,-27,17,-135
5,Scottie Barnes,TOR,SG,PF,-5,-121,16,-137,-51,-8,-15,-20,5,-61
6,Keegan Murray,SAC,SF,PF,1,155,62,93,52,-87,20,4,19,230
7,RJ Barrett,TOR,SG,SF,-26,-490,-186,-304,-144,-162,-184,-86,-53,-527
8,Naz Reid,MIN,PF,C,-3,-72,-54,-18,5,-57,-75,3,-17,-48
9,Caris LeVert,CLE,SG,SF,7,522,184,338,118,173,206,66,73,564
10,Jalen Suggs,ORL,SG,PG,40,233,143,90,46,88,76,30,107,376
11,Daniel Gafford,DAL,PF,C,-10,-217,0,-217,-140,-187,-34,-38,-72,-377
12,Josh Hart,NYK,SF,SG,-35,-91,6,-97,-90,-62,-122,-40,-30,-290
13,Jaden McDaniels,MIN,SF,PF,-11,-206,-48,-158,-49,-246,-62,-8,-6,-243
14,OG Anunoby,NYK,SF,PF,-51,-771,-356,-415,-183,-256,-129,-64,-115,-1007
15,Sam Hauser,BOS,SF,PF,-6,84,66,18,8,52,18,9,12,107
16,Malaki Branham,SAS,PG,SG,29,438,184,254,30,97,118,57,65,455
17,Isaac Okoro,CLE,SF,SG,20,213,64,149,91,76,64,31,36,310
18,Andrew Nembhard,IND,PG,SG,-18,-17,-4,-13,-80,-75,-46,-11,-6,-27
19,Precious Achiuwa,NYK,PF,C,8,-28,14,-42,1,34,-2,9,22,-7
20,Miles McBride,NYK,PG,SG,4,-93,-46,-47,-14,-61,-73,-11,0,-49
21,Trayce Jackson-Davis,GSW,PF,C,-21,30,-2,32,30,30,-22,4,35,133
22,Isaiah Stewart,DET,PF,C,41,67,122,-55,-2,-94,-50,-2,-84,68
23,Zach LaVine,CHI,SG,SF,-19,-334,-136,-198,-79,-73,-91,-69,-7,-520
24,Amir Coffey,LAC,SF,SG,0,-158,-63,-95,-58,-13,-1,-12,-18,-233
25,Pat Connaughton,MIL,SF,SG,2,170,157,13,27,130,91,25,54,212
26,Haywood Highsmith,MIA,PF,SF,-16,-62,-41,-21,-7,-42,-42,-20,-47,-73
27,Matisse Thybulle,POR,SF,SG,14,229,183,46,14,84,62,27,79,242
28,Xavier Tillman Sr.,BOS,PF,C,0,13,-4,17,3,11,13,-9,-3,46
29,Jaylin Williams,OKC,C,PF,-8,7,-9,16,11,-28,-10,-1,19,-2
30,Jared Butler,WAS,SG,PG,0,25,37,-12,-9,17,44,21,18,31
31,John Konchar,MEM,SF,SG,19,117,58,59,17,106,68,30,44,123
32,Julian Strawther,DEN,SF,SG,-4,-264,-131,-133,-59,-81,-36,-34,-97,-361
33,KJ Martin,PHI,SF,PF,-5,72,2,70,10,56,31,18,35,60
34,Maxi Kleber,DAL,C,PF,3,50,43,7,26,48,25,5,13,88
35,Sandro Mamukelashvili,SAS,C,PF,5,-126,-97,-29,-24,-40,1,-7,-25,-195
36,Ricky Council IV,PHI,SG,SF,-12,-351,-181,-170,-82,-168,-81,-47,-50,-359
37,Ousmane Dieng,OKC,PF,C,-1,-9,-1,-8,0,-30,6,1,-11,-9
38,Micah Potter,UTA,PF,C,-10,-95,-77,-18,-12,-121,-25,-26,-36,-109
39,Adama Sanogo,CHI,PF,C,0,20,0,20,12,30,-1,4,4,28
40,JD Davison,BOS,SG,PG,0,-22,-11,-11,-3,-3,-3,-11,2,-17
41,Jordan Walsh,BOS,SF,PF,0,-68,-46,-22,-10,-49,-14,-14,-19,-67